// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class AdjustmentType
{
    public int AdjustmentTypeId { get; set; }

    public string Name { get; set; }

    public string NameInBangla { get; set; }

    public bool IsActive { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedTime { get; set; }

    public virtual ICollection<Adjustment> Adjustments { get; set; } = new List<Adjustment>();

    public virtual ICollection<SalesPriceAdjustment> SalesPriceAdjustments { get; set; } = new List<SalesPriceAdjustment>();
}