// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ApiTransactionType
{
    public int ApiTransactionTypeId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ApiTransaction> ApiTransactions { get; set; } = new List<ApiTransaction>();
}