// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ApiTransaction
{
    public long ApiTransactionId { get; set; }

    public int ApiTransactionTypeId { get; set; }

    public string SecurityToken { get; set; }

    public int NumberOfItem { get; set; }

    public string ApiData { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public virtual ApiTransactionType ApiTransactionType { get; set; }
}