// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class BillOfMaterial
{
    public long BillOfMaterialId { get; set; }

    public long ProductionReceiveId { get; set; }

    public int RawMaterialId { get; set; }

    public decimal UsedQuantity { get; set; }

    public int MeasurementUnitId { get; set; }

    public decimal ConversionRatio { get; set; }

    public long ProductTransactionBookId { get; set; }

    public string ReferenceKey { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public virtual MeasurementUnit MeasurementUnit { get; set; }

    public virtual ProductTransactionBook ProductTransactionBook { get; set; }

    public virtual ICollection<ProductTransactionBook> ProductTransactionBooks { get; set; } = new List<ProductTransactionBook>();

    public virtual ProductionReceive ProductionReceive { get; set; }

    public virtual Product RawMaterial { get; set; }
}