// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class BusinessCategory
{
    public int BusinessCategoryId { get; set; }

    public string Name { get; set; }

    public string NameInBangla { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<Organization> Organizations { get; set; } = new List<Organization>();

    public virtual ICollection<Vendor> Vendors { get; set; } = new List<Vendor>();
}