// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ContractualProductionProductDetail
{
    public int ContractualProductionProductDetailsId { get; set; }

    public int ContractualProductionId { get; set; }

    public int ProductId { get; set; }

    public decimal Quantity { get; set; }

    public int MeasurementUnitId { get; set; }

    public decimal ConversionRatio { get; set; }

    public string ReferenceKey { get; set; }

    public virtual ContractualProduction ContractualProduction { get; set; }

    public virtual MeasurementUnit MeasurementUnit { get; set; }

    public virtual Product Product { get; set; }
}