// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ContractualProduction
{
    public int ContractualProductionId { get; set; }

    public int? ContractTypeId { get; set; }

    public int OrganizationId { get; set; }

    public string ChallanNo { get; set; }

    public string ContractNo { get; set; }

    public int? VendorId { get; set; }

    public int? CustomerId { get; set; }

    public DateTime? IssueDate { get; set; }

    public DateTime ContractDate { get; set; }

    public bool IsClosed { get; set; }

    public DateTime ClosingDate { get; set; }

    public int? ClosedBy { get; set; }

    public string ReferenceKey { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedTime { get; set; }

    public long? ApiTransactionId { get; set; }

    public virtual ContractType ContractType { get; set; }

    public virtual ICollection<ContractualProductionProductDetail> ContractualProductionProductDetails { get; set; } = new List<ContractualProductionProductDetail>();

    public virtual ICollection<ContractualProductionTransferRawMaterial> ContractualProductionTransferRawMaterials { get; set; } = new List<ContractualProductionTransferRawMaterial>();

    public virtual Customer Customer { get; set; }

    public virtual ICollection<ProductionReceive> ProductionReceives { get; set; } = new List<ProductionReceive>();

    public virtual Vendor Vendor { get; set; }
}