// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ContractualProductionTransferRawMaterial
{
    public int ContractualProductionTransferRawMaterialId { get; set; }

    public int ContractualProductionId { get; set; }

    public DateTime TransfereDate { get; set; }

    public string Location { get; set; }

    public string ChallanNo { get; set; }

    public DateTime ChallanIssueDate { get; set; }

    public string ReferenceKey { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public long? ApiTransactionId { get; set; }

    public int? VehicleTypeId { get; set; }

    public string VehicleName { get; set; }

    public string VehicleRegNo { get; set; }

    public string VehicleDriverName { get; set; }

    public string VehicleDriverContactNo { get; set; }

    public virtual ContractualProduction ContractualProduction { get; set; }

    public virtual ICollection<ContractualProductionTransferRawMaterialDetail> ContractualProductionTransferRawMaterialDetails { get; set; } = new List<ContractualProductionTransferRawMaterialDetail>();

    public virtual VehicleType VehicleType { get; set; }
}