// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class Country
{
    public int CountryId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Customer> CustomerBankBranchCountries { get; set; } = new List<Customer>();

    public virtual ICollection<Customer> CustomerCountries { get; set; } = new List<Customer>();

    public virtual ICollection<DivisionOrState> DivisionOrStates { get; set; } = new List<DivisionOrState>();

    public virtual ICollection<MushakReturnPayment> MushakReturnPayments { get; set; } = new List<MushakReturnPayment>();

    public virtual ICollection<OrgBranch> OrgBranches { get; set; } = new List<OrgBranch>();

    public virtual ICollection<TdsPayment> TdsPayments { get; set; } = new List<TdsPayment>();

    public virtual ICollection<Vendor> VendorBankBranchCountries { get; set; } = new List<Vendor>();

    public virtual ICollection<Vendor> VendorCountries { get; set; } = new List<Vendor>();
}