// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class Currency
{
    public int CurrencyId { get; set; }

    public string CurrencyName { get; set; }

    public string CurrencyCode { get; set; }

    public string CurrencySymbol { get; set; }

    public bool IsDefaultCurrency { get; set; }
}