// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class CustomsAndVatcommissionarate
{
    public int CustomsAndVatcommissionarateId { get; set; }

    public string Name { get; set; }

    public string NameInBangla { get; set; }

    public int DistrictId { get; set; }

    public string Address { get; set; }

    public string OperationalCode { get; set; }

    public string OperationalCode1stDigit { get; set; }

    public string OperationalCode2ndDigit { get; set; }

    public string OperationalCode3rdDigit { get; set; }

    public string OperationalCode4thDigit { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<MushakReturnPayment> MushakReturnPayments { get; set; } = new List<MushakReturnPayment>();

    public virtual ICollection<Organization> Organizations { get; set; } = new List<Organization>();

    public virtual ICollection<PurchaseImportTaxPayment> PurchaseImportTaxPayments { get; set; } = new List<PurchaseImportTaxPayment>();

    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();

    public virtual ICollection<TdsPayment> TdsPayments { get; set; } = new List<TdsPayment>();

    public virtual ICollection<Vendor> Vendors { get; set; } = new List<Vendor>();
}