// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class CustomerSubscriptionDetail
{
    public int CustomerSubscriptionDetailId { get; set; }

    public int CustomerSubscriptionId { get; set; }

    public int ProductId { get; set; }

    public int MeasurementUnitId { get; set; }

    public decimal ConversionRatio { get; set; }

    public decimal Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal SupplementaryDutyPercent { get; set; }

    public int ProductVatTypeId { get; set; }

    public decimal ProductVatPercent { get; set; }

    public string Description { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedTime { get; set; }

    public virtual CustomerSubscription CustomerSubscription { get; set; }

    public virtual MeasurementUnit MeasurementUnit { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductVattype ProductVatType { get; set; }

    public virtual ICollection<SubscriptionBillDetail> SubscriptionBillDetails { get; set; } = new List<SubscriptionBillDetail>();
}