// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class DamageDetail
{
    public int DamageDetailId { get; set; }

    public int DamageId { get; set; }

    public int ProductId { get; set; }

    public int? SalesDetailId { get; set; }

    public int? PurchaseDetailId { get; set; }

    public decimal DamageQty { get; set; }

    public decimal UsableQty { get; set; }

    public decimal? UsablePercent { get; set; }

    public int MeasurementUnitId { get; set; }

    public decimal ConversionRatio { get; set; }

    public decimal SuggestedNewUnitPrice { get; set; }

    public string DamageDescription { get; set; }

    public decimal? ApprovedUsableQty { get; set; }

    public decimal? ApprovedNewUnitPrice { get; set; }

    public virtual Damage Damage { get; set; }

    public virtual MeasurementUnit MeasurementUnit { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductTransactionBook> ProductTransactionBooks { get; set; } = new List<ProductTransactionBook>();

    public virtual PurchaseDetail PurchaseDetail { get; set; }

    public virtual SalesDetail SalesDetail { get; set; }
}