// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class DamageType
{
    public int DamageTypeId { get; set; }

    public string Name { get; set; }

    public string NameInBangla { get; set; }

    public virtual ICollection<Damage> Damages { get; set; } = new List<Damage>();
}