// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class DefaultPercent
{
    public byte DefaultPercentId { get; set; }

    public string DefaultPercentFor { get; set; }

    public decimal DefaultPercentValue { get; set; }
}