// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class DistrictOrCity
{
    public int DistrictOrCityId { get; set; }

    public int OrganizationId { get; set; }

    public int DivisionOrStateId { get; set; }

    public string DistrictOrCityName { get; set; }

    public string DistrictOrCityShortName { get; set; }

    public string ReferenceKey { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedTime { get; set; }

    public virtual DivisionOrState DivisionOrState { get; set; }

    public virtual ICollection<MushakReturnPayment> MushakReturnPayments { get; set; } = new List<MushakReturnPayment>();

    public virtual Organization Organization { get; set; }

    public virtual ICollection<TdsPayment> TdsPayments { get; set; } = new List<TdsPayment>();
}