// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class District
{
    public int DistrictId { get; set; }

    public string Name { get; set; }

    public string NameInBangla { get; set; }

    public virtual ICollection<OrgBranch> OrgBranches { get; set; } = new List<OrgBranch>();

    public virtual ICollection<PurchaseImportTaxPayment> PurchaseImportTaxPayments { get; set; } = new List<PurchaseImportTaxPayment>();
}