// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ExcelUploadedDataType
{
    public int ExcelUploadedDataTypeId { get; set; }

    public string ExcelUploadedDataTypeName { get; set; }

    public virtual ICollection<ExcelDataUpload> ExcelDataUploads { get; set; } = new List<ExcelDataUpload>();
}