// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ExportType
{
    public int ExportTypeId { get; set; }

    public string ExportTypeName { get; set; }

    public string ExportTypeNameInBangla { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}