// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class MeasurementUnit
{
    public int MeasurementUnitId { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public int OrganizationId { get; set; }

    public bool IsActive { get; set; }

    public string ReferenceKey { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedTime { get; set; }

    public long? ApiTransactionId { get; set; }

    public long? ExcelDataUploadId { get; set; }

    public virtual ICollection<BillOfMaterial> BillOfMaterials { get; set; } = new List<BillOfMaterial>();

    public virtual ICollection<BranchTransferReceiveDetail> BranchTransferReceiveDetails { get; set; } = new List<BranchTransferReceiveDetail>();

    public virtual ICollection<BranchTransferSendDetail> BranchTransferSendDetails { get; set; } = new List<BranchTransferSendDetail>();

    public virtual ICollection<ByProductReceive> ByProductReceives { get; set; } = new List<ByProductReceive>();

    public virtual ICollection<ContractualProductionProductDetail> ContractualProductionProductDetails { get; set; } = new List<ContractualProductionProductDetail>();

    public virtual ICollection<ContractualProductionTransferRawMaterialDetail> ContractualProductionTransferRawMaterialDetails { get; set; } = new List<ContractualProductionTransferRawMaterialDetail>();

    public virtual ICollection<CreditNoteDetail> CreditNoteDetails { get; set; } = new List<CreditNoteDetail>();

    public virtual ICollection<CustomerSubscriptionDetail> CustomerSubscriptionDetails { get; set; } = new List<CustomerSubscriptionDetail>();

    public virtual ICollection<DamageDetail> DamageDetails { get; set; } = new List<DamageDetail>();

    public virtual ICollection<DebitNoteDetail> DebitNoteDetails { get; set; } = new List<DebitNoteDetail>();

    public virtual ICollection<PriceSetupProductCost> PriceSetupProductCosts { get; set; } = new List<PriceSetupProductCost>();

    public virtual ICollection<PriceSetup> PriceSetups { get; set; } = new List<PriceSetup>();

    public virtual ICollection<ProductMeasurementUnit> ProductMeasurementUnits { get; set; } = new List<ProductMeasurementUnit>();

    public virtual ICollection<ProductOpeningBalance> ProductOpeningBalances { get; set; } = new List<ProductOpeningBalance>();

    public virtual ICollection<ProductTransactionBook> ProductTransactionBooks { get; set; } = new List<ProductTransactionBook>();

    public virtual ICollection<ProductUsedInService> ProductUsedInServices { get; set; } = new List<ProductUsedInService>();

    public virtual ICollection<ProductionReceive> ProductionReceives { get; set; } = new List<ProductionReceive>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; } = new List<PurchaseDetail>();

    public virtual ICollection<SalesDetail> SalesDetails { get; set; } = new List<SalesDetail>();

    public virtual ICollection<SalesPriceAdjustmentDetail> SalesPriceAdjustmentDetails { get; set; } = new List<SalesPriceAdjustmentDetail>();

    public virtual ICollection<SubscriptionBillDetail> SubscriptionBillDetails { get; set; } = new List<SubscriptionBillDetail>();
}