// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class MushakSubmissionType
{
    public byte MushakSubmissionTypeId { get; set; }

    public string SubmissionTypeName { get; set; }

    public string SubmissionTypeNameBn { get; set; }

    public virtual ICollection<MushakSubmission> MushakSubmissions { get; set; } = new List<MushakSubmission>();
}