// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class MushakGenerationStage
{
    public byte MushakGenerationStageId { get; set; }

    public string Name { get; set; }

    public string NameInBangla { get; set; }
}