// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class MushakGeneration
{
    public int MushakGenerationId { get; set; }

    public int OrganizationId { get; set; }

    public int MushakForYear { get; set; }

    public int MushakForMonth { get; set; }

    public DateTime GenerateDate { get; set; }

    public virtual ICollection<CreditNote> CreditNotes { get; set; } = new List<CreditNote>();

    public virtual ICollection<DebitNote> DebitNotes { get; set; } = new List<DebitNote>();

    public virtual Organization Organization { get; set; }
}