// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class MushakReturnPaymentForVd
{
    public int MushakReturnPaymentForVdsId { get; set; }

    public int MushakReturnPaymentId { get; set; }

    public int PurchaseId { get; set; }

    public decimal VdsPaidAmount { get; set; }

    public virtual MushakReturnPayment MushakReturnPayment { get; set; }

    public virtual Purchase Purchase { get; set; }
}