// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class NbrEconomicCodeType
{
    public int NbrEconomicCodeTypeId { get; set; }

    public string CodeTypeName { get; set; }

    public virtual ICollection<NbrEconomicCode> NbrEconomicCodes { get; set; } = new List<NbrEconomicCode>();
}