// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class OldAccountCurrentBalance
{
    public int OldAccountCurrentBalanceId { get; set; }

    public int OrganizationId { get; set; }

    public int MushakYear { get; set; }

    public int MushakMonth { get; set; }

    public decimal RemainingVatbalance { get; set; }

    public decimal RemainingSdbalance { get; set; }

    public string ReferenceKey { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public long? ApiTransactionId { get; set; }

    public virtual Organization Organization { get; set; }
}