// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class OrganizationConfigurationIntType
{
    public int OrganizationConfigurationIntTypeId { get; set; }

    public int OrganizationConfigurationAreaId { get; set; }

    public string OrganizationConfigurationIntTypeName { get; set; }

    public int DefaultValue { get; set; }

    public virtual OrganizationConfigurationArea OrganizationConfigurationArea { get; set; }
}