// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class OrganizationConfigurationBooleanType
{
    public int OrganizationConfigurationBooleanTypeId { get; set; }

    public int OrganizationConfigurationAreaId { get; set; }

    public string OrganizationConfigurationBooleanTypeName { get; set; }

    public bool DefaultValue { get; set; }

    public virtual OrganizationConfigurationArea OrganizationConfigurationArea { get; set; }
}