// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class OrganizationConfigType
{
    public int OrganizationConfigTypeId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<OrganizationConfig> OrganizationConfigs { get; set; } = new List<OrganizationConfig>();
}