// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class Organization
{
    public int OrganizationId { get; set; }

    public string Name { get; set; }

    public int? ParentOrganizationId { get; set; }

    public string Code { get; set; }

    public string VatregNo { get; set; }

    public string Bin { get; set; }

    public int CustomsAndVatcommissionarateId { get; set; }

    public int FinancialActivityNatureId { get; set; }

    public int BusinessNatureId { get; set; }

    public int BusinessCategoryId { get; set; }

    public string BusinessCategoryDescription { get; set; }

    public bool? IsProductionCompany { get; set; }

    public bool IsDeductVatInSource { get; set; }

    public bool IsSellStandardVatProduct { get; set; }

    public string CertificateNo { get; set; }

    public string EmailAddress { get; set; }

    public string Mobile { get; set; }

    public string Address { get; set; }

    public int CountryId { get; set; }

    public int CityId { get; set; }

    public string VatResponsiblePersonName { get; set; }

    public string VatResponsiblePersonDesignation { get; set; }

    public string VatResponsiblePersonMobileNo { get; set; }

    public string VatResponsiblePersonEmailAddress { get; set; }

    public string VatResponsiblePersonSignUrl { get; set; }

    public bool IsActive { get; set; }

    public int? EnlistedNo { get; set; }

    public int? PostalCode { get; set; }

    public bool? IsSaleSimplified { get; set; }

    public bool? IsImposeServiceCharge { get; set; }

    public decimal? ServiceChargePercent { get; set; }

    public bool? IsUserSignInSalesTaxInvoice { get; set; }

    public bool? IsRequireSku { get; set; }

    public bool? IsRequireSkuId { get; set; }

    public bool? IsRequireGoodsId { get; set; }

    public bool? IsRequirePartNo { get; set; }

    public bool? IsRequireComplecatedInformation { get; set; }

    public string InvoiceNameEng { get; set; }

    public string InvoiceNameBan { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedTime { get; set; }

    public virtual ICollection<Adjustment> Adjustments { get; set; } = new List<Adjustment>();

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual ICollection<Bank> Banks { get; set; } = new List<Bank>();

    public virtual ICollection<BranchTransferReceive> BranchTransferReceives { get; set; } = new List<BranchTransferReceive>();

    public virtual ICollection<BranchTransferSend> BranchTransferSends { get; set; } = new List<BranchTransferSend>();

    public virtual ICollection<Brand> Brands { get; set; } = new List<Brand>();

    public virtual BusinessCategory BusinessCategory { get; set; }

    public virtual BusinessNature BusinessNature { get; set; }

    public virtual ICollection<ByProductReceive> ByProductReceives { get; set; } = new List<ByProductReceive>();

    public virtual ICollection<CustomerBranch> CustomerBranches { get; set; } = new List<CustomerBranch>();

    public virtual ICollection<CustomerCategory> CustomerCategories { get; set; } = new List<CustomerCategory>();

    public virtual ICollection<CustomerDeliveryAddress> CustomerDeliveryAddresses { get; set; } = new List<CustomerDeliveryAddress>();

    public virtual ICollection<CustomerSubscriptionCategory> CustomerSubscriptionCategories { get; set; } = new List<CustomerSubscriptionCategory>();

    public virtual ICollection<CustomerSubscription> CustomerSubscriptions { get; set; } = new List<CustomerSubscription>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual CustomsAndVatcommissionarate CustomsAndVatcommissionarate { get; set; }

    public virtual ICollection<Damage> Damages { get; set; } = new List<Damage>();

    public virtual ICollection<DistrictOrCity> DistrictOrCities { get; set; } = new List<DistrictOrCity>();

    public virtual ICollection<DivisionOrState> DivisionOrStates { get; set; } = new List<DivisionOrState>();

    public virtual ICollection<DocumentType> DocumentTypes { get; set; } = new List<DocumentType>();

    public virtual FinancialActivityNature FinancialActivityNature { get; set; }

    public virtual ICollection<MushakGeneration> MushakGenerations { get; set; } = new List<MushakGeneration>();

    public virtual ICollection<MushakReturnPayment> MushakReturnPayments { get; set; } = new List<MushakReturnPayment>();

    public virtual ICollection<MushakReturnRefund> MushakReturnRefunds { get; set; } = new List<MushakReturnRefund>();

    public virtual ICollection<MushakSubmission> MushakSubmissions { get; set; } = new List<MushakSubmission>();

    public virtual ICollection<OldAccountCurrentBalance> OldAccountCurrentBalances { get; set; } = new List<OldAccountCurrentBalance>();

    public virtual ICollection<OrgBranch> OrgBranches { get; set; } = new List<OrgBranch>();

    public virtual ICollection<OrgStaticDatum> OrgStaticData { get; set; } = new List<OrgStaticDatum>();

    public virtual ICollection<OrganizationConfig> OrganizationConfigs { get; set; } = new List<OrganizationConfig>();

    public virtual ICollection<PriceSetup> PriceSetups { get; set; } = new List<PriceSetup>();

    public virtual ICollection<ProductCategory> ProductCategories { get; set; } = new List<ProductCategory>();

    public virtual ICollection<ProductGroup> ProductGroups { get; set; } = new List<ProductGroup>();

    public virtual ICollection<ProductMeasurementUnit> ProductMeasurementUnits { get; set; } = new List<ProductMeasurementUnit>();

    public virtual ICollection<ProductOpeningBalance> ProductOpeningBalances { get; set; } = new List<ProductOpeningBalance>();

    public virtual ICollection<ProductTransactionBook> ProductTransactionBooks { get; set; } = new List<ProductTransactionBook>();

    public virtual ICollection<ProductUsedInService> ProductUsedInServices { get; set; } = new List<ProductUsedInService>();

    public virtual ICollection<ProductionReceive> ProductionReceives { get; set; } = new List<ProductionReceive>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<Purchase> PurchaseOrganizations { get; set; } = new List<Purchase>();

    public virtual ICollection<Purchase> PurchaseTransferBranches { get; set; } = new List<Purchase>();

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();

    public virtual ICollection<Sale> SaleOrganizations { get; set; } = new List<Sale>();

    public virtual ICollection<Sale> SaleOtherBranchOrganizations { get; set; } = new List<Sale>();

    public virtual ICollection<SalesPriceAdjustment> SalesPriceAdjustments { get; set; } = new List<SalesPriceAdjustment>();

    public virtual ICollection<SubscriptionBill> SubscriptionBills { get; set; } = new List<SubscriptionBill>();

    public virtual ICollection<SupplimentaryDuty> SupplimentaryDuties { get; set; } = new List<SupplimentaryDuty>();

    public virtual ICollection<TdsPayment> TdsPayments { get; set; } = new List<TdsPayment>();

    public virtual ICollection<UserBranch> UserBranches { get; set; } = new List<UserBranch>();

    public virtual ICollection<UserLoginHistory> UserLoginHistories { get; set; } = new List<UserLoginHistory>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();

    public virtual ICollection<VehicleType> VehicleTypes { get; set; } = new List<VehicleType>();

    public virtual ICollection<VendorBranch> VendorBranches { get; set; } = new List<VendorBranch>();

    public virtual ICollection<VendorCategory> VendorCategories { get; set; } = new List<VendorCategory>();

    public virtual ICollection<Vendor> Vendors { get; set; } = new List<Vendor>();
}