// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class OrganizationConfigurationArea
{
    public int OrganizationConfigurationAreaId { get; set; }

    public string OrganizationConfigurationAreaName { get; set; }

    public virtual ICollection<OrganizationConfigurationBooleanType> OrganizationConfigurationBooleanTypes { get; set; } = new List<OrganizationConfigurationBooleanType>();

    public virtual ICollection<OrganizationConfigurationDecimalType> OrganizationConfigurationDecimalTypes { get; set; } = new List<OrganizationConfigurationDecimalType>();

    public virtual ICollection<OrganizationConfigurationIntType> OrganizationConfigurationIntTypes { get; set; } = new List<OrganizationConfigurationIntType>();

    public virtual ICollection<OrganizationConfigurationStringType> OrganizationConfigurationStringTypes { get; set; } = new List<OrganizationConfigurationStringType>();
}