// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class OrgStaticDataType
{
    public int OrgStaticDataTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<OrgStaticDatum> OrgStaticData { get; set; } = new List<OrgStaticDatum>();
}