// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class OverHeadCost
{
    public int OverHeadCostId { get; set; }

    public int? OrganizationId { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public bool IsApplicableAsRawMaterial { get; set; }

    public string ReferenceKey { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedTime { get; set; }

    public long? ApiTransactionId { get; set; }

    public virtual ICollection<PriceSetupProductCost> PriceSetupProductCosts { get; set; } = new List<PriceSetupProductCost>();
}