// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class PriceSetup
{
    public int PriceSetupId { get; set; }

    public int OrganizationId { get; set; }

    public int ProductId { get; set; }

    public int MeasurementUnitId { get; set; }

    public decimal? BaseTp { get; set; }

    public decimal? Mrp { get; set; }

    public decimal PurchaseUnitPrice { get; set; }

    public decimal SalesUnitPrice { get; set; }

    public decimal ProfitAmount { get; set; }

    public bool? IsMushakSubmitted { get; set; }

    public int? SubmissionSl { get; set; }

    public DateTime? MushakSubmissionDate { get; set; }

    public DateTime EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public bool IsActive { get; set; }

    public string ReferenceKey { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public long? ApiTransactionId { get; set; }

    public virtual MeasurementUnit MeasurementUnit { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual ICollection<PriceSetupProductCost> PriceSetupProductCosts { get; set; } = new List<PriceSetupProductCost>();

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductionReceive> ProductionReceives { get; set; } = new List<ProductionReceive>();
}