// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class Product
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public int? BrandId { get; set; }

    public string ProductNumber { get; set; }

    public string ModelNo { get; set; }

    public string DeviceModel { get; set; }

    public string Code { get; set; }

    public string PartNo { get; set; }

    public string PartCode { get; set; }

    public string Variant { get; set; }

    public string Color { get; set; }

    public string Size { get; set; }

    public string Weight { get; set; }

    public decimal? WeightInKg { get; set; }

    public string Specification { get; set; }

    public string Hscode { get; set; }

    public int? ProductCategoryId { get; set; }

    public int ProductGroupId { get; set; }

    public int ProductTypeId { get; set; }

    public int OrganizationId { get; set; }

    public decimal TotalQuantity { get; set; }

    public int MeasurementUnitId { get; set; }

    public string Description { get; set; }

    public DateTime EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public string ReferenceKey { get; set; }

    public DateTime? ModifyDate { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedTime { get; set; }

    public long? ApiTransactionId { get; set; }

    public bool IsNonRebateable { get; set; }

    public long? ExcelDataUploadId { get; set; }

    public virtual ICollection<BillOfMaterial> BillOfMaterials { get; set; } = new List<BillOfMaterial>();

    public virtual ICollection<BranchTransferReceiveDetail> BranchTransferReceiveDetails { get; set; } = new List<BranchTransferReceiveDetail>();

    public virtual ICollection<BranchTransferSendDetail> BranchTransferSendDetails { get; set; } = new List<BranchTransferSendDetail>();

    public virtual Brand Brand { get; set; }

    public virtual ICollection<ByProductReceive> ByProductReceives { get; set; } = new List<ByProductReceive>();

    public virtual ICollection<ContractualProductionProductDetail> ContractualProductionProductDetails { get; set; } = new List<ContractualProductionProductDetail>();

    public virtual ICollection<ContractualProductionTransferRawMaterialDetail> ContractualProductionTransferRawMaterialDetails { get; set; } = new List<ContractualProductionTransferRawMaterialDetail>();

    public virtual ICollection<CustomerSubscriptionDetail> CustomerSubscriptionDetails { get; set; } = new List<CustomerSubscriptionDetail>();

    public virtual ICollection<DamageDetail> DamageDetails { get; set; } = new List<DamageDetail>();

    public virtual MeasurementUnit MeasurementUnit { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual ICollection<PriceSetupProductCost> PriceSetupProductCosts { get; set; } = new List<PriceSetupProductCost>();

    public virtual ICollection<PriceSetup> PriceSetups { get; set; } = new List<PriceSetup>();

    public virtual ProductCategory ProductCategory { get; set; }

    public virtual ProductGroup ProductGroup { get; set; }

    public virtual ICollection<ProductMeasurementUnit> ProductMeasurementUnits { get; set; } = new List<ProductMeasurementUnit>();

    public virtual ICollection<ProductOpeningBalance> ProductOpeningBalances { get; set; } = new List<ProductOpeningBalance>();

    public virtual ICollection<ProductTransactionBook> ProductTransactionBooks { get; set; } = new List<ProductTransactionBook>();

    public virtual ProductType ProductType { get; set; }

    public virtual ICollection<ProductUsedInService> ProductUsedInServices { get; set; } = new List<ProductUsedInService>();

    public virtual ICollection<ProductVat> ProductVats { get; set; } = new List<ProductVat>();

    public virtual ICollection<ProductionReceive> ProductionReceives { get; set; } = new List<ProductionReceive>();

    public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; } = new List<PurchaseDetail>();

    public virtual ICollection<SalesDetail> SalesDetails { get; set; } = new List<SalesDetail>();

    public virtual ICollection<SalesPriceAdjustmentDetail> SalesPriceAdjustmentDetails { get; set; } = new List<SalesPriceAdjustmentDetail>();

    public virtual ICollection<SubscriptionBillDetail> SubscriptionBillDetails { get; set; } = new List<SubscriptionBillDetail>();

    public virtual ICollection<SupplimentaryDuty> SupplimentaryDuties { get; set; } = new List<SupplimentaryDuty>();
}