// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ProductVattype
{
    public int ProductVattypeId { get; set; }

    public string Name { get; set; }

    public string NameInBangla { get; set; }

    public decimal DefaultVatPercent { get; set; }

    public bool IsVatapplicable { get; set; }

    public DateTime EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public bool IsApplicableForLocalPurchase { get; set; }

    public bool IsApplicableForImport { get; set; }

    public bool IsApplicableForLocalSale { get; set; }

    public bool IsApplicableForExport { get; set; }

    public bool IsRequireVds { get; set; }

    public string LocalPurchaseNote { get; set; }

    public string LocalPurchaseNoteInBn { get; set; }

    public string ImportNote { get; set; }

    public string ImportNoteInBn { get; set; }

    public string LocalSaleNote { get; set; }

    public string LocalSaleNoteInBn { get; set; }

    public string ExportNote { get; set; }

    public string ExportNoteInBn { get; set; }

    public bool IsVatUpdatable { get; set; }

    public bool? IsRebatable { get; set; }

    public virtual ICollection<CustomerSubscriptionDetail> CustomerSubscriptionDetails { get; set; } = new List<CustomerSubscriptionDetail>();

    public virtual ICollection<ProductVat> ProductVats { get; set; } = new List<ProductVat>();

    public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; } = new List<PurchaseDetail>();

    public virtual ICollection<SalesDetail> SalesDetails { get; set; } = new List<SalesDetail>();

    public virtual ICollection<SubscriptionBillDetail> SubscriptionBillDetails { get; set; } = new List<SubscriptionBillDetail>();
}