// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class PurchaseImportTaxPayment
{
    public int PurchaseImportTaxPaymentId { get; set; }

    public int PurchaseImportTaxPaymentTypeId { get; set; }

    public int PurchaseId { get; set; }

    public int PitpVatCommissionarateId { get; set; }

    public int PitpBankId { get; set; }

    public string PitpBankBranchName { get; set; }

    public int PitpBankBranchDistrictId { get; set; }

    public string PitpAccCode { get; set; }

    public string PitpDocOrChallanNo { get; set; }

    public DateTime PitpDocOrChallanDate { get; set; }

    public DateTime PitpPaymentDate { get; set; }

    public decimal PitpPaidAmount { get; set; }

    public string PitpPaymentRemarks { get; set; }

    public virtual Bank PitpBank { get; set; }

    public virtual District PitpBankBranchDistrict { get; set; }

    public virtual CustomsAndVatcommissionarate PitpVatCommissionarate { get; set; }

    public virtual Purchase Purchase { get; set; }

    public virtual PurchaseImportTaxPaymentType PurchaseImportTaxPaymentType { get; set; }
}