// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class PurchaseImportTariff
{
    public long PurchaseImportTariffId { get; set; }

    public string HsCode { get; set; }

    public string ItemDescription { get; set; }

    public decimal IdPercent { get; set; }

    public decimal CdPercent { get; set; }

    public decimal SdPercent { get; set; }

    public decimal VatPercent { get; set; }

    public decimal AitPercent { get; set; }

    public decimal RdPercent { get; set; }

    public decimal AtPercent { get; set; }

    public decimal? TtiPercent { get; set; }

    public int ProductVatTypeId { get; set; }

    public bool IsActive { get; set; }

    public DateTime EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }
}