// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class PurchaseImportTaxPaymentType
{
    public int PurchaseImportTaxPaymentTypeId { get; set; }

    public string PaymentTypeName { get; set; }

    public string PaymentTypeShortName { get; set; }

    public bool IsTotal { get; set; }

    public virtual ICollection<PurchaseImportTaxPayment> PurchaseImportTaxPayments { get; set; } = new List<PurchaseImportTaxPayment>();
}