// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class SalesDeliveryType
{
    public int SalesDeliveryTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeliveryDetailRequired { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}