// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class SalesPriceAdjustmentDetail
{
    public int SalesPriceAdjustmentDetailId { get; set; }

    public int SalesPriceAdjustmentId { get; set; }

    public int ProductId { get; set; }

    public int SalesDetailId { get; set; }

    public decimal QuantityToChange { get; set; }

    public decimal ChangeAmountPerItem { get; set; }

    public int MeasurementUnitId { get; set; }

    public string ReasonOfChange { get; set; }

    public string ReferenceKey { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public virtual MeasurementUnit MeasurementUnit { get; set; }

    public virtual Product Product { get; set; }

    public virtual SalesDetail SalesDetail { get; set; }

    public virtual SalesPriceAdjustment SalesPriceAdjustment { get; set; }
}