// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class SalesDetailBreakdown
{
    public long SalesDetailBreakdownId { get; set; }

    public int SalesId { get; set; }

    public string RefId { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public virtual Sale Sales { get; set; }
}