// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class Sale
{
    public int SalesId { get; set; }

    public string InvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public string VatChallanNo { get; set; }

    public string EmhCode { get; set; }

    public int OrganizationId { get; set; }

    public int? OrgBranchId { get; set; }

    public int SalesSlNo { get; set; }

    public int NoOfIteams { get; set; }

    public decimal TotalPriceWithoutVat { get; set; }

    public decimal DiscountOnTotalPrice { get; set; }

    public decimal TotalDiscountOnIndividualProduct { get; set; }

    public decimal TotalVat { get; set; }

    public decimal TotalSupplimentaryDuty { get; set; }

    public bool IsVatDeductedInSource { get; set; }

    public DateTime? Vdsdate { get; set; }

    public decimal? Vdsamount { get; set; }

    public bool? IsVdscertificateReceived { get; set; }

    public string VdscertificateNo { get; set; }

    public DateTime? VdscertificateIssueTime { get; set; }

    public int? VdspaymentBankId { get; set; }

    public string VdspaymentBankBranchName { get; set; }

    public DateTime? VdspaymentDate { get; set; }

    public string VdspaymentChallanNo { get; set; }

    public string VdspaymentEconomicCode { get; set; }

    public string VdspaymentBookTransferNo { get; set; }

    public string Vdsnote { get; set; }

    public bool? IsTds { get; set; }

    public DateTime? TdsDate { get; set; }

    public decimal? TdsAmount { get; set; }

    public bool? IsTdsCertificateReceived { get; set; }

    public string TdsCertificateNo { get; set; }

    public DateTime? TdsCertificateIssueTime { get; set; }

    public int? TdsPaymentBankId { get; set; }

    public string TdsPaymentBankBranchName { get; set; }

    public DateTime? TdsPaymentDate { get; set; }

    public string TdsPaymentChallanNo { get; set; }

    public string TdsPaymentEconomicCode { get; set; }

    public string TdsPaymentBookTransferNo { get; set; }

    public string TdsNote { get; set; }

    public decimal? ReceivableAmount { get; set; }

    public decimal? PaymentReceiveAmount { get; set; }

    public decimal? PaymentDueAmount { get; set; }

    public int? CustomerId { get; set; }

    public string CustomerName { get; set; }

    public string CustomerBin { get; set; }

    public string CustomerNid { get; set; }

    public string CustomerAddress { get; set; }

    public string CustomerPhoneNo { get; set; }

    public string ReceiverName { get; set; }

    public string ReceiverContactNo { get; set; }

    public string ShippingAddress { get; set; }

    public int? ShippingCountryId { get; set; }

    public int SalesTypeId { get; set; }

    public int SalesDeliveryTypeId { get; set; }

    public string WorkOrderNo { get; set; }

    public DateTime SalesDate { get; set; }

    public DateTime? ExpectedDeliveryDate { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public int? DeliveryMethodId { get; set; }

    public int? ExportTypeId { get; set; }

    public string LcNo { get; set; }

    public DateTime? LcDate { get; set; }

    public string BillOfEntry { get; set; }

    public DateTime? BillOfEntryDate { get; set; }

    public DateTime? DueDate { get; set; }

    public string TermsOfLc { get; set; }

    public string CustomerPoNumber { get; set; }

    public bool IsComplete { get; set; }

    public bool IsTaxInvoicePrined { get; set; }

    public DateTime? TaxInvoicePrintedTime { get; set; }

    public bool? IsTaxInvoiceGenerated { get; set; }

    public DateTime? TaxInvoiceGeneratedTime { get; set; }

    public string VatResponsiblePersonName { get; set; }

    public string VatResponsiblePersonDesignation { get; set; }

    public string VatResponsiblePersonMobileNo { get; set; }

    public string VatResponsiblePersonEmailAddress { get; set; }

    public string VatResponsiblePersonSignUrl { get; set; }

    public int? MushakGenerationId { get; set; }

    public int? OtherBranchOrganizationId { get; set; }

    public string TransferChallanNo { get; set; }

    public DateTime? TransferChallanPrintedTime { get; set; }

    public string ReferenceKey { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public long? ApiTransactionId { get; set; }

    public int? VehicleTypeId { get; set; }

    public string VehicleName { get; set; }

    public string VehicleRegNo { get; set; }

    public string VehicleDriverName { get; set; }

    public string VehicleDriverContactNo { get; set; }

    public string SalesRemarks { get; set; }

    public long? ExcelDataUploadId { get; set; }

    public bool? IsApproved { get; set; }

    public int? ApprovedBy { get; set; }

    public string ApproveMessage { get; set; }

    public bool? IsRejected { get; set; }

    public int? RejectedBy { get; set; }

    public string RejectMessage { get; set; }

    public virtual ICollection<CreditNote> CreditNotes { get; set; } = new List<CreditNote>();

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Damage> Damages { get; set; } = new List<Damage>();

    public virtual DeliveryMethod DeliveryMethod { get; set; }

    public virtual ExportType ExportType { get; set; }

    public virtual OrgBranch OrgBranch { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Organization OtherBranchOrganization { get; set; }

    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();

    public virtual SalesDeliveryType SalesDeliveryType { get; set; }

    public virtual ICollection<SalesDetailBreakdown> SalesDetailBreakdowns { get; set; } = new List<SalesDetailBreakdown>();

    public virtual ICollection<SalesDetail> SalesDetails { get; set; } = new List<SalesDetail>();

    public virtual ICollection<SalesPaymentReceive> SalesPaymentReceives { get; set; } = new List<SalesPaymentReceive>();

    public virtual ICollection<SalesPriceAdjustment> SalesPriceAdjustments { get; set; } = new List<SalesPriceAdjustment>();

    public virtual SalesType SalesType { get; set; }

    public virtual ICollection<SubscriptionBill> SubscriptionBills { get; set; } = new List<SubscriptionBill>();

    public virtual Bank VdspaymentBank { get; set; }

    public virtual VehicleType VehicleType { get; set; }
}