// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class SubscriptionBill
{
    public int SubscriptionBillId { get; set; }

    public int? CustomerSubscriptionId { get; set; }

    public int OrganizationId { get; set; }

    public int OrgBranchId { get; set; }

    public int CollectionOfficeId { get; set; }

    public int CustomerId { get; set; }

    public int? SalesId { get; set; }

    public int BillYear { get; set; }

    public int BillMonth { get; set; }

    public string Remarks { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedTime { get; set; }

    public virtual OrgBranch CollectionOffice { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual CustomerSubscription CustomerSubscription { get; set; }

    public virtual OrgBranch OrgBranch { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Sale Sales { get; set; }

    public virtual ICollection<SubscriptionBillDetail> SubscriptionBillDetails { get; set; } = new List<SubscriptionBillDetail>();
}