// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class TdsPayment
{
    public int TdsPaymentId { get; set; }

    public int OrganizationId { get; set; }

    public int CustomsAndVatcommissionarateId { get; set; }

    public int MushakYear { get; set; }

    public int MushakMonth { get; set; }

    public decimal PaidAmount { get; set; }

    public DateTime PaymentDate { get; set; }

    public int BankId { get; set; }

    public string BankBranchName { get; set; }

    public int BankBranchCountryId { get; set; }

    public int BankBranchDistrictOrCityId { get; set; }

    public string EconomicCode1stDisit { get; set; }

    public string EconomicCode2ndDisit { get; set; }

    public string EconomicCode3rdDisit { get; set; }

    public string EconomicCode4thDisit { get; set; }

    public string EconomicCode5thDisit { get; set; }

    public string EconomicCode6thDisit { get; set; }

    public string EconomicCode7thDisit { get; set; }

    public string EconomicCode8thDisit { get; set; }

    public string EconomicCode9thDisit { get; set; }

    public string EconomicCode10thDisit { get; set; }

    public string EconomicCode11thDisit { get; set; }

    public string EconomicCode12thDisit { get; set; }

    public string EconomicCode13thDisit { get; set; }

    public bool IsSubmitted { get; set; }

    public string TreasuryChallanNo { get; set; }

    public DateTime? SubimissionDate { get; set; }

    public int? SubmissionEntryBy { get; set; }

    public DateTime? SubmissionEntryDate { get; set; }

    public string ReferenceKey { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public long? ApiTransactionId { get; set; }

    public virtual Bank Bank { get; set; }

    public virtual Country BankBranchCountry { get; set; }

    public virtual DistrictOrCity BankBranchDistrictOrCity { get; set; }

    public virtual CustomsAndVatcommissionarate CustomsAndVatcommissionarate { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual ICollection<TdsPaymentForPurchase> TdsPaymentForPurchases { get; set; } = new List<TdsPaymentForPurchase>();
}