// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class User
{
    public int UserId { get; set; }

    public string FullName { get; set; }

    public string UserName { get; set; }

    public string EmployeeId { get; set; }

    public string EmployeePin { get; set; }

    public string Designation { get; set; }

    public string EmailAddress { get; set; }

    public string Mobile { get; set; }

    public string NidNo { get; set; }

    public string TinNo { get; set; }

    public string ReferenceTicketNo { get; set; }

    public string Address { get; set; }

    public string UserImageUrl { get; set; }

    public string UserSignUrl { get; set; }

    public string Password { get; set; }

    public int UserTypeId { get; set; }

    public int RoleId { get; set; }

    public int? OrganizationId { get; set; }

    public bool? IsRequireBranch { get; set; }

    public bool IsActive { get; set; }

    public string InActivationReason { get; set; }

    public DateTime? InActivationTime { get; set; }

    public int? InActivatedBy { get; set; }

    public bool? IsLocked { get; set; }

    public string Remarks { get; set; }

    public DateTime? LastLockTime { get; set; }

    public string LastLockReason { get; set; }

    public int? LastUnlockedBy { get; set; }

    public DateTime? LastUnlockTime { get; set; }

    public DateTime? LastLoginTime { get; set; }

    public int? AccessFailedCount { get; set; }

    public bool IsDefaultPassword { get; set; }

    public bool IsCompanyRepresentative { get; set; }

    public string ReferenceKey { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual Organization Organization { get; set; }

    public virtual Role Role { get; set; }

    public virtual ICollection<UserBranch> UserBranches { get; set; } = new List<UserBranch>();

    public virtual ICollection<UserLoginHistory> UserLoginHistories { get; set; } = new List<UserLoginHistory>();

    public virtual UserType UserType { get; set; }
}