// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class VehicleType
{
    public int VehicleTypeId { get; set; }

    public int OrganizationId { get; set; }

    public string VehicleTypeName { get; set; }

    public bool IsRequireRegistration { get; set; }

    public string Description { get; set; }

    public string ReferenceKey { get; set; }

    public bool IsActive { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedTime { get; set; }

    public virtual ICollection<BranchTransferReceive> BranchTransferReceives { get; set; } = new List<BranchTransferReceive>();

    public virtual ICollection<BranchTransferSend> BranchTransferSends { get; set; } = new List<BranchTransferSend>();

    public virtual ICollection<ContractualProductionTransferRawMaterial> ContractualProductionTransferRawMaterials { get; set; } = new List<ContractualProductionTransferRawMaterial>();

    public virtual ICollection<CreditNote> CreditNotes { get; set; } = new List<CreditNote>();

    public virtual Organization Organization { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}