// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class VendorType
{
    public int VendorTypeId { get; set; }

    public string VendorTypeName { get; set; }

    public bool IsForeign { get; set; }

    public virtual ICollection<Vendor> Vendors { get; set; } = new List<Vendor>();
}