// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ViewSalesPaymentAgingReport
{
    public long? SlNo { get; set; }

    public int? OrganizationId { get; set; }

    public string OrganizationName { get; set; }

    public string OrganizationBin { get; set; }

    public string OrganizationAddress { get; set; }

    public int CustomerId { get; set; }

    public string CustomerName { get; set; }

    public string CustomerBinNo { get; set; }

    public string CustomerAddress { get; set; }

    public string CustomerContactNo { get; set; }

    public string CustomerEmailAddress { get; set; }

    public decimal? ZeroToThirtyDays { get; set; }

    public decimal? ThirtyOneToSixtyDays { get; set; }

    public decimal? SixtyOneToNinetyDays { get; set; }

    public decimal? NinetyToOneTwentyDays { get; set; }

    public decimal? MoreThanOneTwentyDays { get; set; }
}