// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ViewSubscriptionBill
{
    public int SubscriptionBillId { get; set; }

    public int? CustomerSubscriptionId { get; set; }

    public int OrganizationId { get; set; }

    public int BillingOfficeId { get; set; }

    public string BillingOfficeName { get; set; }

    public string BillingOfficeAddress { get; set; }

    public int CollectionOfficeId { get; set; }

    public string CollectionOfficeName { get; set; }

    public string CollectionOfficeAddress { get; set; }

    public int CustomerId { get; set; }

    public string CustomerName { get; set; }

    public string CustomerBinOrNidNo { get; set; }

    public string PhoneNo { get; set; }

    public string CustomerAddress { get; set; }

    public int? SalesId { get; set; }

    public bool? IsSentToSales { get; set; }

    public string IsSentToSalesStatus { get; set; }

    public string InvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public string TaxInvoiceNo { get; set; }

    public DateTime? TaxInvoiceIssueTime { get; set; }

    public int BillYear { get; set; }

    public int BillMonth { get; set; }

    public string BillMonthName { get; set; }

    public decimal? SubscriptionPriceWithoutTax { get; set; }

    public decimal? SupplementaryDuty { get; set; }

    public decimal? VatAmount { get; set; }
}