// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ViewCreditNote
{
    public int OrganizationId { get; set; }

    public string OrganizationName { get; set; }

    public string OrganizationAddress { get; set; }

    public string OrganizationBin { get; set; }

    public int? BranchId { get; set; }

    public DateTime? CreditNoteCreatedTime { get; set; }

    public string CreditNoteChallanNo { get; set; }

    public string ReasonOfReturn { get; set; }

    public DateTime CreditNoteReturnDate { get; set; }

    public DateTime? CreditNoteChallanPrintTime { get; set; }

    public int CreditNoteId { get; set; }

    public int SalesId { get; set; }

    public string SalesVatChallanNo { get; set; }

    public DateTime? SalesInvoiceDate { get; set; }

    public DateTime SalesDate { get; set; }

    public string SalesTypeName { get; set; }

    public int CustomerId { get; set; }

    public string CustomerName { get; set; }

    public string CustomerBinNo { get; set; }

    public string SalesInvoiceNo { get; set; }

    public decimal SalesTotalPriceWithoutVat { get; set; }

    public decimal SalesTotalVat { get; set; }

    public decimal? SalesVdsAmount { get; set; }

    public decimal? SalesReceivableAmount { get; set; }

    public decimal? SalesPaymentDueAmount { get; set; }

    public decimal? SalesPaymentReceiveAmount { get; set; }

    public bool IsVatDeductedInSource { get; set; }

    public bool? IsVdscertificateReceived { get; set; }
}