// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ViewProductVat
{
    public long? SlFromLast { get; set; }

    public int ProductVatid { get; set; }

    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int ProductVattypeId { get; set; }

    public string ProductVatTypeName { get; set; }

    public bool IsVatUpdatable { get; set; }

    public decimal DefaultVatPercent { get; set; }
}