// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ViewInputOutputCoEfficient
{
    public int PriceSetupId { get; set; }

    public decimal? BaseTp { get; set; }

    public decimal? Mrp { get; set; }

    public decimal PurchaseUnitPrice { get; set; }

    public decimal SalesUnitPrice { get; set; }

    public decimal ProfitAmount { get; set; }

    public bool? IsMushakSubmitted { get; set; }

    public int? SubmissionSl { get; set; }

    public DateTime? MushakSubmissionDate { get; set; }

    public DateTime EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public int ProductId { get; set; }

    public bool IsActive { get; set; }

    public string ActivationStatus { get; set; }

    public string ProductName { get; set; }

    public int? BrandId { get; set; }

    public string ProductNumber { get; set; }

    public string ModelNo { get; set; }

    public string DeviceModel { get; set; }

    public string Code { get; set; }

    public string PartNo { get; set; }

    public string PartCode { get; set; }

    public string Variant { get; set; }

    public string Color { get; set; }

    public string Size { get; set; }

    public string Weight { get; set; }

    public string Specification { get; set; }

    public string Hscode { get; set; }

    public int? ProductCategoryId { get; set; }

    public int ProductGroupId { get; set; }

    public int ProductTypeId { get; set; }

    public decimal TotalQuantity { get; set; }

    public bool IsNonRebateable { get; set; }

    public decimal? MaterialCost { get; set; }

    public decimal? OverheadCost { get; set; }

    public int MeasurementUnitId { get; set; }

    public string MeasurementUnitName { get; set; }

    public string ProductTypeName { get; set; }

    public string ProductCategoryName { get; set; }

    public string BrandName { get; set; }

    public int OrganizationId { get; set; }

    public string OrganizationName { get; set; }

    public string OrganizationBin { get; set; }

    public string OrganizationAddress { get; set; }
}