// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ViewOrganizationConfigurationBoolean
{
    public int OrganizationId { get; set; }

    public int OrganizationConfigurationBooleanTypeId { get; set; }

    public string OrganizationConfigurationBooleanTypeName { get; set; }

    public bool ConfigurationValue { get; set; }
}