// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ViewProductMeasurementUnit
{
    public int ProductId { get; set; }

    public int MeasurementUnitId { get; set; }

    public decimal? ConvertionRatio { get; set; }

    public string MeasurementUnitName { get; set; }
}