// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ViewPurchaseImport
{
    public int PurchaseId { get; set; }

    public int OrganizationId { get; set; }

    public string OrganizationName { get; set; }

    public int? OrgBranchId { get; set; }

    public string BranchName { get; set; }

    public int PurchaseSlNo { get; set; }

    public DateTime PurchaseDate { get; set; }

    public string InvoiceNo { get; set; }

    public DateTime InvoiceDate { get; set; }

    public string VoucherNo { get; set; }

    public DateTime VoucherDate { get; set; }

    public string CommercialInvoiceNo { get; set; }

    public DateTime CommercialInvoiceDate { get; set; }

    public string BillOfEntryNo { get; set; }

    public DateTime? BillOfEntryDate { get; set; }

    public int? VendorId { get; set; }

    public string VendorName { get; set; }

    public decimal? TotalPriceWithoutTax { get; set; }

    public decimal? CustomDutyAmount { get; set; }

    public decimal? ImportDutyAmount { get; set; }

    public decimal? RegulatoryDutyAmount { get; set; }

    public decimal? AdvanceIncomeTaxAmount { get; set; }

    public decimal? SupplementaryDutyAmount { get; set; }

    public decimal? VatAmount { get; set; }

    public decimal? AdvanceTaxAmount { get; set; }

    public decimal? VatOrAtImposablePrice { get; set; }

    public bool IsComplete { get; set; }

    public string IsCompleteStatus { get; set; }

    public bool? IsApproved { get; set; }

    public string IsApprovedStatus { get; set; }

    public bool? IsRejected { get; set; }

    public string IsRejectedStatus { get; set; }

    public string ApproveStatus { get; set; }
}