// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vms.entity.models;

public partial class ViewDebitNote
{
    public int OrganizationId { get; set; }

    public string OrganizationName { get; set; }

    public string OrganizationAddress { get; set; }

    public string OrganizationBin { get; set; }

    public int DebitNoteId { get; set; }

    public DateTime? DebitNoteCreatedTime { get; set; }

    public string DebitNoteChallanNo { get; set; }

    public string ReasonOfReturn { get; set; }

    public DateTime DebitNoteReturnDate { get; set; }

    public DateTime? DebitNoteChallanPrintTime { get; set; }

    public int? BranchId { get; set; }

    public int PurchaseId { get; set; }

    public string PurchaseVatChallanNo { get; set; }

    public DateTime? PurchaseVatChallanIssueDate { get; set; }

    public DateTime PurchaseDate { get; set; }

    public string PurchaseTypeName { get; set; }

    public int VendorId { get; set; }

    public string VendorName { get; set; }

    public string VendorBinNo { get; set; }

    public string PurchaseInvoiceNo { get; set; }

    public string PurchaseVoucherNo { get; set; }

    public decimal PurchaseTotalPriceWithoutVat { get; set; }

    public decimal PurchaseTotalVat { get; set; }

    public decimal? PurchaseVdsAmount { get; set; }

    public decimal? PurchasePayableAmount { get; set; }

    public decimal? PurchaseDueAmount { get; set; }

    public decimal? PurchasePaidAmount { get; set; }

    public bool IsVatDeductedInSource { get; set; }

    public bool? IsVdsCertificatePrinted { get; set; }
}