namespace vms.utility.StaticData;

public static class ControllerStaticData
{
    public const string HOME = "Home";
    public const string NODE = "Node";
    public const string SALES = "Sales";
    public const string VALUE = "Value";
    public const string ADMIN = "Admin";
    public const string REASON = "Reason";
    public const string VENDOR = "Vendor";
    public const string USER_ID = "UserId";
    public const string ROLE_ID = "RoleId";
    public const string COMPANY = "Company";
    public const string MESSAGE = "message";
    public const string SESSION = "session";
    public const string RIGHT_ID = "RightId";
    public const string NBR_USER = "NbrUser";
    public const string PURCHASE = "Purchase";
    public const string CUSTOMER = "Customer";
    public const string USER_OBJECT = "Users";
    public const string USER_NAME = "UserName";
    public const string VENDOR_ID = "VendorId";
    public const string ROLE_NAME = "RoleName";
    public const string INDEX_DEV = "Index_dev";
    public const string DISPLAY_INDEX = "Index";
    public const string TEXT_CLASSNAME = "Text";
    public const string PRODUCT_ID = "ProductId";

    public const string FRATURE_ID = "FeatureId";
    public const string RIGHT_NAME = "RightName";
    public const string CREATED_ON = "CreatedOn";
    public const string CREATED_BY = "CreatedBy";
    public const string USER_AGENT = "User-Agent";
    public const string ERROR_CLASSNAME = "Error";
    public const string ErrorIndicator = "Error: ";
    public const string DUPLICATE_CLASSNAME = "Duplicate";
    public const char AUDIT_OBJECT_TYPE_NAME = 's';
    public const string LIST_PRODUCTS = "Products";
    public const string EXCISE_DUTY = "ExciseDuty";

    public const string DELETE_CLASSNAME = "InActive";
    public const string ACTIVE_CLASSNAME = "Active";
    public const string IN_ACTIVE_CLASSNAME = "InActive";
    public const string SAVED_CLASSNAME = "Saved";
    public const string USER_TYPE_ID = "UserTypeId";
    public const string CREATED_TIME = "CreatedTime";
    public const string CREATED_DATE = "CreatedDate";
    public const string DISPLAY_NAME = "DisplayName";
    public const string EFFECTIVE_TO = "EffectiveTo";
    public const string DETAIL_IS_NEW = "DetailsNew";
    public const string IS_SUBMITTED = "IsSubmitted";
    public const string AUDIT_PRIMARY_KEY_NAME = "Id";
    public const string WORK_ORDER_ID = "WorkOrderId";
    public const string EMAIL_ADDRESS = "EmailAddress";
    public const string SESSION_CLASSNAME = "session";
    public const string ROLE_RIGHT_ID = "RoleRightId";
    public const string SALES_TYPE_ID = "SalesTypeId";
    public const string SUCCESS_CLASSNAME = "Success";
    public const string UPDATE_CLASSNAME = "Updated";
    public const string PRODUCTION_ID = "ProductionId";
    public const string SEARCH_VENDOR = "searchVendor";
    public const string USER_TYPE_NAME = "UserTypeName";
    public const string EXPORT_TYPE_ID = "ExportTypeId";
    public const string DAMAGED_DESCRIPTION = "Damaged";
    public const string DAMAGE_TYPE_ID = "DamageTypeId";
    public const string DISPLAY_DASHBOARD = "Dashboard";

    public const string EFFECTIVE_FROM = "EffectiveFrom";
    public const string ENCRYPTION_KEY = "EncryptionKey";
    public const string AUTHENTICATION = "Authentication";
    public const string PAID_VAT_AMOUNT = "PaidVatAmount";
    public const string SALES_TYPE_NAME = "SalesTypeName";
    public const string MUSHAK_FOR_YEAR = "MushakForYear";
    public const string PARENT_GROUP_ID = "ParentGroupId";
    public const string SEARCH_PRODUCT = "searchProduct";
    public const string ORGANIZATION_ID = "OrganizationId";
    public const string SUBMISSION_DATE = "SubmissionDate";
    public const string DOCUMENT_TYPE_ID = "DocumentTypeId";
    public const string PURCHASE_TYPE_ID = "PurchaseTypeId";
    public const string PRODUCT_GROUP_ID = "ProductGroupId";
    public const string MUSHAK_FOR_MONTH = "MushakForMonth";
    public const string PAID_EXCISE_DUTY = "PaidExciseDuty";
    public const string PAYMENT_METHOD_ID = "PaymentMethodId";
    public const string APPLICATION_JSON = "appsettings.json";
    public const string MUSHAK_GENERATE_DATE = "GenerateDate";
    public const string FINANCIAL_PENALTY = "FinancialPenalty";
    public const string RESPONSE_TYPE_JSON = "application/json";
    public const string PURCHASE_REASON_ID = "PurchaseReasonId";
    public const string DELIVERY_METHOD_ID = "DeliveryMethodId";
    public const string PAID_AMOUNT_FOR_VAT = "PaidAmountForVat";
    public const string PRODUCT_VAT_TYPE_ID = "ProductVattypeId";
    public const string PRODUCT_CATEGORY_ID = "ProductCategoryId";
    public const string DEFAULT_VAT_PERCENT = "DefaultVatPercent";
    public const string TRANSACTION_TYPE_ID = "TransactionTypeId";
    public const string ROLE_DEFAULT_PAGE_ID = "RoleDefaultPageId";
    public const string INTEREST_FOR_DUE_VAT = "InterestForDueVat";
    public const string MUSHAK_GENERATION_ID = "MushakGenerationId";
    public const string PAID_SUPP_DUTY_AMOUNT = "PaidSuppDutyAmount";
    public const string APPLICATION_DOCUMENT = "ApplicationDocument/";
    public const string SALES_DELIVERY_TYPE_ID = "SalesDeliveryTypeId";
    public const string DEVELOPMENT_SURCHARGE = "DevelopmentSurcharge";
    public const string PAID_FINANCIAL_PENALTY = "PaidFinancialPenalty";
    public const string LAST_CLOSING_VAT_AMOUNT = "LastClosingVatAmount";
    public const string IT_DEVELOPMENT_SURCHARGE = "ItDevelopmentSurcharge";
    public const string PAID_AMOUNT_FOR_SUPP_DUTY = "PaidAmountForSuppDuty";
    public const string INTEREST_FOR_DUE_SUPP_DUTY = "InterestForDueSuppDuty";
    public const string IS_COMPANY_REPRESENTATIVE = "IsCompanyRepresentative";
    public const string PAID_DEVELOPMENT_SURCHARGE = "PaidDevelopmentSurcharge";
    public const string SUPPLEMENTARY_DUTY_PERCENT = "SupplementaryDutyPercent";
    public const string PRIVATE_DATA_ENCRYPTION_KEY = "PrivateData:EncryptionKey";
    public const string PRIVATE_DATA_URL = "PrivateData:Port";
    public const string LAST_CLOSING_SUPP_DUTY_AMOUNT = "LastClosingSuppDutyAmount";
    public const string HEALTH_DEVELOPMENT_SURCHARGE = "HealthDevelopmentSurcharge";
    public const string PAID_IT_DEVELOPMENT_SURCHARGE = "PaidItDevelopmentSurcharge";
    public const string ENVIRONMENT_PROTECT_SURCHARGE = "EnvironmentProtectSurcharge";
    public const string PRIVATE_DATA_DEFAULT_PASSWORD = "PrivateData:DefaultPassword";
    public const string PAID_INTEREST_AMOUNT_FOR_DUE_VAT = "PaidInterestAmountForDueVat";
    public const string PAID_HEALTH_DEVELOPMENT_SURCHARGE = "PaidHealthDevelopmentSurcharge";
    public const string PAID_ENVIRONMENT_PROTECT_SURCHARGE = "PaidEnvironmentProtectSurcharge";
    public const string PAID_INTEREST_AMOUNT_FOR_DUE_SUPP_DUTY = "PaidInterestAmountForDueSuppDuty";
    public const string EMPTY_CLASSNAME = "Empty";

    public const string NotFount = "NotFound";


    public const string FileRootPath = @"wwwroot/UploadedFiles";
    public const string FilePurchaseModulePath = "Purchase";
    public const string FileSaleModulePath = "Sales";
    public const string FileSalesBreakdownModulePath = "SalesBreakdown";
    public const string FileCustomerPath = "Customer";
    public const string FileVendorPath = "Vendor";

    public const string FileUploadedSimplifiedLocalSalePath = "UploadedSimplifiedLocalSale";
    public const string FileUploadedSimplifiedLocalPurchasePath = "UploadedSimplifiedLocalPurchase";
    public const string FileUploadedUserImagePath = "UserImage";
    public const string FileUploadedUserSignaturePath = "UserImage";


    public static string SavedSuccessMessage = "Saved successfully!";
}