CREATE TABLE [dbo].[Organizations] (
    [OrganizationId]                   INT            IDENTITY (1, 1) NOT NULL,
    [Name]                             NVARCHAR (50)  NOT NULL,
    [ParentOrganizationId]             INT            NULL,
    [Code]                             NVARCHAR (50)  NULL,
    [VATRegNo]                         NVARCHAR (50)  NULL,
    [BIN]                              NVARCHAR (50)  NULL,
    [CustomsAndVATCommissionarateId]   INT            NOT NULL,
    [FinancialActivityNatureId]        INT            NOT NULL,
    [BusinessNatureId]                 INT            NOT NULL,
    [BusinessCategoryId]               INT            NOT NULL,
    [BusinessCategoryDescription]      NVARCHAR (500) NULL,
    [IsDeductVatInSource]              BIT            NOT NULL,
    [IsSellStandardVatProduct]         BIT            NOT NULL,
    [CertificateNo]                    NVARCHAR (50)  NULL,
    [Address]                          NVARCHAR (200) NOT NULL,
    [CountryId]                        INT            NOT NULL,
    [CityId]                           INT            NOT NULL,
    [VatResponsiblePersonName]         NVARCHAR (100) NOT NULL,
    [VatResponsiblePersonDesignation]  NVARCHAR (50)  NOT NULL,
    [VatResponsiblePersonMobileNo]     NVARCHAR (100) NOT NULL,
    [VatResponsiblePersonEmailAddress] NVARCHAR (100) NOT NULL,
    [IsActive]                         BIT            NOT NULL,
    [EnlistedNo]                       INT            NULL,
    [PostalCode]                       INT            NULL,
    [CreatedBy]                        INT            NULL,
    [CreatedTime]                      DATETIME       NULL,
    [ModifiedBy]                       INT            NULL,
    [ModifiedTime]                     DATETIME       NULL,
    CONSTRAINT [PK_Organizations] PRIMARY KEY CLUSTERED ([OrganizationId] ASC),
    CONSTRAINT [FK_Organizations_BusinessCategory] FOREIGN KEY ([BusinessCategoryId]) REFERENCES [dbo].[BusinessCategory] ([BusinessCategoryId]),
    CONSTRAINT [FK_Organizations_BusinessNature] FOREIGN KEY ([BusinessNatureId]) REFERENCES [dbo].[BusinessNature] ([BusinessNatureId]),
    CONSTRAINT [FK_Organizations_CustomsAndVATCommissionarate] FOREIGN KEY ([CustomsAndVATCommissionarateId]) REFERENCES [dbo].[CustomsAndVATCommissionarate] ([CustomsAndVATCommissionarateId]),
    CONSTRAINT [FK_Organizations_FinancialActivityNature] FOREIGN KEY ([FinancialActivityNatureId]) REFERENCES [dbo].[FinancialActivityNature] ([FinancialActivityNatureId])
);

