CREATE TABLE [dbo].[Sales] (
    [SalesId]                          INT             IDENTITY (1, 1) NOT NULL,
    [InvoiceNo]                        NVARCHAR (50)   NOT NULL,
    [VatChallanNo]                     NVARCHAR (50)   NULL,
    [OrganizationId]                   INT             NOT NULL,
    [NoOfIteams]                       INT             NOT NULL,
    [TotalPriceWithoutVat]             DECIMAL (18, 2) NOT NULL,
    [DiscountOnTotalPrice]             DECIMAL (18, 2) NOT NULL,
    [TotalDiscountOnIndividualProduct] DECIMAL (18, 2) NOT NULL,
    [TotalVAT]                         DECIMAL (18, 2) NOT NULL,
    [TotalSupplimentaryDuty]           DECIMAL (18, 2) NOT NULL,
    [IsVatDeductedInSource]            BIT             NOT NULL,
    [VDSAmount]                        DECIMAL (18, 2) NULL,
    [IsVDSCertificateReceived]         BIT             NULL,
    [VDSCertificateNo]                 NVARCHAR (50)   NULL,
    [VDSCertificateIssueTime]          DATETIME        NULL,
    [VDSPaymentBankBranchId]           INT             NULL,
    [VDSPaymentDate]                   DATETIME        NULL,
    [VDSPaymentChallanNo]              NVARCHAR (20)   NULL,
    [VDSPaymentEconomicCode]           NVARCHAR (20)   NULL,
    [VDSPaymentBookTransferNo]         NVARCHAR (50)   NULL,
    [VDSNote]                          NVARCHAR (500)  NULL,
    [ReceivableAmount]                 AS              (CONVERT([decimal](21,2),case when [IsVatDeductedInSource]=(1) then [TotalPriceWithoutVat]-[DiscountOnTotalPrice] else ([TotalPriceWithoutVat]+[TotalVAT])-[DiscountOnTotalPrice] end)),
    [PaymentReceiveAmount]             DECIMAL (18, 2) NULL,
    [PaymentDueAmount]                 AS              (CONVERT([decimal](21,2),case when [IsVatDeductedInSource]=(1) then [TotalPriceWithoutVat]-[DiscountOnTotalPrice] else ([TotalPriceWithoutVat]+[TotalVAT])-[DiscountOnTotalPrice] end)-[PaymentReceiveAmount]),
    [CustomerId]                       INT             NULL,
    [ReceiverName]                     NVARCHAR (200)  NULL,
    [ReceiverContactNo]                VARCHAR (20)    NULL,
    [ShippingAddress]                  NVARCHAR (200)  NULL,
    [ShippingCountryId]                INT             NULL,
    [SalesTypeId]                      INT             NOT NULL,
    [SalesDeliveryTypeId]              INT             CONSTRAINT [DF__tmp_ms_xx__Sales__7D439ABD] DEFAULT ((1)) NOT NULL,
    [WorkOrderNo]                      NVARCHAR (50)   NULL,
    [SalesDate]                        DATETIME        NOT NULL,
    [ExpectedDeliveryDate]             DATETIME        NULL,
    [DeliveryDate]                     DATETIME        NULL,
    [DeliveryMethodId]                 INT             NULL,
    [ExportTypeId]                     INT             NULL,
    [LcNo]                             NVARCHAR (50)   NULL,
    [LcDate]                           DATETIME        NULL,
    [BillOfEntry]                      NVARCHAR (50)   NULL,
    [BillOfEntryDate]                  DATETIME        NULL,
    [DueDate]                          DATETIME        NULL,
    [TermsOfLc]                        NVARCHAR (500)  NULL,
    [CustomerPoNumber]                 NVARCHAR (50)   NULL,
    [IsComplete]                       BIT             NOT NULL,
    [IsTaxInvoicePrined]               BIT             NOT NULL,
    [TaxInvoicePrintedTime]            DATETIME        NULL,
    [MushakGenerationId]               INT             NULL,
    [OtherBranchOrganizationId]        INT             NULL,
    [TransferChallanNo]                NVARCHAR (50)   NULL,
    [TransferChallanPrintedTime]       DATETIME        NULL,
    [ReferenceKey]                     NVARCHAR (100)  NULL,
    [CreatedBy]                        INT             NULL,
    [CreatedTime]                      DATETIME        NULL,
    [ApiTransactionId]                 BIGINT          NULL,
    CONSTRAINT [PK_Sales] PRIMARY KEY CLUSTERED ([SalesId] ASC),
    CONSTRAINT [FK_Sales_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customer] ([CustomerId]),
    CONSTRAINT [FK_Sales_DeliveryMethod] FOREIGN KEY ([DeliveryMethodId]) REFERENCES [dbo].[DeliveryMethod] ([DeliveryMethodId]),
    CONSTRAINT [FK_Sales_ExportType] FOREIGN KEY ([ExportTypeId]) REFERENCES [dbo].[ExportType] ([ExportTypeId]),
    CONSTRAINT [FK_Sales_Organizations] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[Organizations] ([OrganizationId]),
    CONSTRAINT [FK_Sales_OtherBranchOrganization] FOREIGN KEY ([OtherBranchOrganizationId]) REFERENCES [dbo].[Organizations] ([OrganizationId]),
    CONSTRAINT [FK_Sales_SalesDeliveryType] FOREIGN KEY ([SalesDeliveryTypeId]) REFERENCES [dbo].[SalesDeliveryType] ([SalesDeliveryTypeId]),
    CONSTRAINT [FK_Sales_SalesType] FOREIGN KEY ([SalesTypeId]) REFERENCES [dbo].[SalesType] ([SalesTypeId])
);

