namespace vms.entity.viewModels;

public class FeatureList
{
    public const string NBR_USER = "NBR_USER";
    public const string DASHBOARD = "DASHBOARD";
    public const string ADMINSTRATION = "ADMINSTRATION";
       
    public const string ADMINSTRATION_COMPANY_BASIC_INFO_CAN_VIEW = "ADMINSTRATION_COMPANY_BASIC_INFO_CAN_VIEW";
    public const string ADMINSTRATION_COMPANY_BASIC_INFO_CAN_ADD = "ADMINSTRATION_COMPANY_BASIC_INFO_CAN_ADD";
    public const string ADMINSTRATION_COMPANY_BASIC_INFO_CAN_EDIT = "ADMINSTRATION_COMPANY_BASIC_INFO_CAN_EDIT";
    public const string ADMINSTRATION_COMPANY_BASIC_INFO_CAN_VIEW_BRANCH_DETAILS = "ADMINSTRATION_COMPANY_BASIC_INFO_CAN_VIEW_BRANCH_DETAILS";
    public const string ADMINSTRATION_COMPANY_BASIC_INFO_CAN_ADD_BRANCH = "ADMINSTRATION_COMPANY_BASIC_INFO_CAN_ADD_BRANCH";
    public const string ADMINSTRATION_COMPANY_BASIC_INFO_CAN_IMPORT_DATA = "ADMINSTRATION_COMPANY_BASIC_INFO_CAN_IMPORT_DATA";
       
    public const string ADMINSTRATION_USERS_CAN_VIEW = "ADMINSTRATION_USERS_CAN_VIEW";
    public const string ADMINSTRATION_USERS_CAN_ADD = "ADMINSTRATION_USERS_CAN_ADD";
    public const string ADMINSTRATION_USERS_CAN_EDIT = "ADMINSTRATION_USERS_CAN_EDIT";
    public const string ADMINSTRATION_USERS_CAN_VIEW_DETAILS = "ADMINSTRATION_USERS_CAN_VIEW_DETAILS";
    public const string ADMINSTRATION_USERS_CAN_DELETE = "ADMINSTRATION_USERS_CAN_DELETE";

	public const string ADMINSTRATION_USERS_CAN_MANAGE_BRANCH = "ADMINSTRATION_USERS_CAN_MANAGE_BRANCH";
	public const string ADMINSTRATION_USERS_CAN_UPDATE_ROLE = "ADMINSTRATION_USERS_CAN_UPDATE_ROLE";
	public const string ADMINSTRATION_USERS_CAN_UPDATE_IMAGE = "ADMINSTRATION_USERS_CAN_UPDATE_IMAGE";
	public const string ADMINSTRATION_USERS_CAN_UPDATE_SIGNATURE = "ADMINSTRATION_USERS_CAN_UPDATE_SIGNATURE";
	public const string ADMINSTRATION_USERS_CAN_UPDATE_PASSWORD = "ADMINSTRATION_USERS_CAN_UPDATE_PASSWORD";

	public const string ADMINSTRATION_ROLES_CAN_VIEW = "ADMINSTRATION_ROLES_CAN_VIEW";
      
    public const string ADMINSTRATION_ROLES_CAN_ADD = "ADMINSTRATION_ROLES_CAN_ADD";
    public const string ADMINSTRATION_ROLES_CAN_EDIT = "ADMINSTRATION_ROLES_CAN_EDIT";
    public const string ADMINSTRATION_ROLES_CAN_ASSIGN_RIGHTS = "ADMINSTRATION_ROLES_CAN_ASSIGN_RIGHTS";
       
    public const string ADMINSTRATION_PRODUCT_CATEGORY_CAN_VIEW = "ADMINSTRATION_PRODUCT_CATEGORY_CAN_VIEW";
       
    public const string ADMINSTRATION_PRODUCT_CATEGORY_CAN_ADD = "ADMINSTRATION_PRODUCT_CATEGORY_CAN_ADD";
    public const string ADMINSTRATION_PRODUCT_CATEGORY_CAN_EDIT = "ADMINSTRATION_PRODUCT_CATEGORY_CAN_EDIT";
    public const string ADMINSTRATION_PRODUCT_CATEGORY_CAN_DELETE = "ADMINSTRATION_PRODUCT_CATEGORY_CAN_DELETE";
    public const string ADMINSTRATION_OVER_HEAD_COST_CAN_VIEW = "ADMINSTRATION_OVER_HEAD_COST_CAN_VIEW";     
    public const string ADMINSTRATION_OVER_HEAD_COST_CAN_ADD = "ADMINSTRATION_OVER_HEAD_COST_CAN_ADD";   
    public const string ADMINSTRATION_DAMAGE_TYPE_CAN_VIEW = "ADMINSTRATION_DAMAGE_TYPE_CAN_VIEW";        
    public const string ADMINSTRATION_DAMAGE_TYPE_CAN_ADD = "ADMINSTRATION_DAMAGE_TYPE_CAN_ADD";
    public const string ADMINSTRATION_DAMAGE_TYPE_CAN_EDIT = "ADMINSTRATION_DAMAGE_TYPE_CAN_EDIT";
    public const string ADMINSTRATION_DAMAGE_TYPE_CAN_DELETE = "ADMINSTRATION_DAMAGE_TYPE_CAN_DELETE"; 
    public const string ADMINSTRATION_DELIVERY_METHOD_CAN_VIEW = "ADMINSTRATION_DELIVERY_METHOD_CAN_VIEW";
    public const string ADMINSTRATION_DOCUMENT_TYPE_CAN_VIEW = "ADMINSTRATION_DOCUMENT_TYPE_CAN_VIEW";
    public const string ADMINSTRATION_DOCUMENT_TYPE_CAN_ADD = "ADMINSTRATION_DOCUMENT_TYPE_CAN_ADD";
    public const string ADMINSTRATION_DOCUMENT_TYPE_CAN_EDIT = "ADMINSTRATION_DOCUMENT_TYPE_CAN_EDIT";
    public const string ADMINSTRATION_DOCUMENT_TYPE_CAN_DELETE = "ADMINSTRATION_DOCUMENT_TYPE_CAN_DELETE";
    public const string ADMINSTRATION_EXPORT_TYPE_CAN_VIEW = "ADMINSTRATION_EXPORT_TYPE_CAN_VIEW";
    public const string ADMINSTRATION_MEASURMENT_UNIT_CAN_VIEW = "ADMINSTRATION_MEASURMENT_UNIT_CAN_VIEW";
    public const string ADMINSTRATION_MEASURMENT_UNIT_CAN_ADD = "ADMINSTRATION_MEASURMENT_UNIT_CAN_ADD";
    public const string ADMINSTRATION_MEASURMENT_UNIT_CAN_EDIT = "ADMINSTRATION_MEASURMENT_UNIT_CAN_EDIT";
    public const string ADMINSTRATION_MEASURMENT_UNIT_CAN_DELETE = "ADMINSTRATION_MEASURMENT_UNIT_CAN_DELETE";

	#region Product Measurment Unit

	public const string ADMINSTRATION_PRODUCT_MEASURMENT_UNIT_CAN_VIEW = "ADMINSTRATION_PRODUCT_MEASURMENT_UNIT_CAN_VIEW";
	public const string ADMINSTRATION_PRODUCT_MEASURMENT_UNIT_CAN_ADD = "ADMINSTRATION_PRODUCT_MEASURMENT_UNIT_CAN_ADD";
	public const string ADMINSTRATION_PRODUCT_MEASURMENT_UNIT_CAN_EDIT = "ADMINSTRATION_PRODUCT_MEASURMENT_UNIT_CAN_EDIT";
	public const string ADMINSTRATION_PRODUCT_MEASURMENT_UNIT_CAN_DELETE = "ADMINSTRATION_PRODUCT_MEASURMENT_UNIT_CAN_DELETE";

    #endregion

    #region Customer Subscription Category
    public const string ADMINSTRATION_CUSTOMER_SUBSCRIPTION_CATEGORY_CAN_ADD = "ADMINSTRATION_CUSTOMER_SUBSCRIPTION_CATEGORY_CAN_ADD";
    public const string ADMINSTRATION_CUSTOMER_SUBSCRIPTION_CATEGORY_CAN_EDIT = "ADMINSTRATION_CUSTOMER_SUBSCRIPTION_CATEGORY_CAN_EDIT";
    public const string ADMINSTRATION_CUSTOMER_SUBSCRIPTION_CATEGORY_CAN_VIEW = "ADMINSTRATION_CUSTOMER_SUBSCRIPTION_CATEGORY_CAN_VIEW";
	#endregion

	#region Customer Category
	public const string ADMINSTRATION_CUSTOMER_CATEGORY_CAN_ADD = "ADMINSTRATION_CUSTOMER_CATEGORY_CAN_ADD";
	public const string ADMINSTRATION_CUSTOMER_CATEGORY_CAN_EDIT = "ADMINSTRATION_CUSTOMER_CATEGORY_CAN_EDIT";
	public const string ADMINSTRATION_CUSTOMER_CATEGORY_CAN_VIEW = "ADMINSTRATION_CUSTOMER_CATEGORY_CAN_VIEW";
	#endregion

	#region Customer Category
	public const string ADMINSTRATION_VENDOR_CATEGORY_CAN_ADD = "ADMINSTRATION_VENDOR_CATEGORY_CAN_ADD";
	public const string ADMINSTRATION_VENDOR_CATEGORY_CAN_EDIT = "ADMINSTRATION_VENDOR_CATEGORY_CAN_EDIT";
	public const string ADMINSTRATION_VENDOR_CATEGORY_CAN_VIEW = "ADMINSTRATION_VENDOR_CATEGORY_CAN_VIEW";
	#endregion

	public const string ADMINSTRATION_PAYMENT_METHODS_CAN_VIEW = "ADMINSTRATION_PAYMENT_METHODS_CAN_VIEW";
    
       
        
    public const string ADMINSTRATION_PRODUCT_GROUPS_CAN_VIEW = "ADMINSTRATION_PRODUCT_GROUPS_CAN_VIEW";
       
    public const string ADMINSTRATION_PRODUCT_GROUPS_CAN_ADD = "ADMINSTRATION_PRODUCT_GROUPS_CAN_ADD";
    public const string ADMINSTRATION_PRODUCT_GROUPS_CAN_EDIT = "ADMINSTRATION_PRODUCT_GROUPS_CAN_EDIT";
    public const string ADMINSTRATION_PRODUCT_GROUPS_CAN_DELETE = "ADMINSTRATION_PRODUCT_GROUPS_CAN_DELETE";
  
    public const string ADMINSTRATION_PRODUCT_VAT_TYPES_CAN_VIEW = "ADMINSTRATION_PRODUCT_VAT_TYPES_CAN_VIEW";
        
   
     
    public const string ADMINSTRATION_PURCHASE_REASONES_CAN_VIEW = "ADMINSTRATION_PURCHASE_REASONES_CAN_VIEW";
        

    public const string ADMINSTRATION_SALES_DELIVERY_TYPE_CAN_VIEW = "ADMINSTRATION_SALES_DELIVERY_TYPE_CAN_VIEW";
        
    
    public const string ADMINSTRATION_MISCELLANEOUS_ADJUSTMENT_CAN_VIEW = "ADMINSTRATION_MISCELLANEOUS_ADJUSTMENT_CAN_VIEW";
        
    public const string ADMINSTRATION_MISCELLANEOUS_ADJUSTMENT_CAN_ADD = "ADMINSTRATION_MISCELLANEOUS_ADJUSTMENT_CAN_ADD";
    public const string ADMINSTRATION_MISCELLANEOUS_ADJUSTMENT_CAN_DELETE = "ADMINSTRATION_MISCELLANEOUS_ADJUSTMENT_CAN_DELETE";
       
    public const string ADMINSTRATION_MISCELLANEOUS_ADJUSTMENT_TYPE_CAN_VIEW = "ADMINSTRATION_MISCELLANEOUS_ADJUSTMENT_TYPE_CAN_VIEW";
        
    public const string ADMINSTRATION_CUSTOMS_AND_VAT_COMMISSIONARATE_CAN_VIEW = "ADMINSTRATION_CUSTOMS_AND_VAT_COMMISSIONARATE_CAN_VIEW";
        
        
    public const string MUSHAK_RETURN = "MUSHAK_RETURN";
        
    public const string MUSHAK_RETURN_REMAINING_AMOUNT_FROM_MUSHAK_18_6_CAN_VIEW = "MUSHAK_RETURN_REMAINING_AMOUNT_FROM_MUSHAK_18_6_CAN_VIEW";

    public const string MUSHAK_RETURN_REMAINING_AMOUNT_FROM_MUSHAK_18_6_CAN_ADD = "MUSHAK_RETURN_REMAINING_AMOUNT_FROM_MUSHAK_18_6_CAN_ADD";
       
    public const string MUSHAK_RETURN_MUSHAK_RETURN_PAYMENT_CAN_VIEW = "MUSHAK_RETURN_MUSHAK_RETURN_PAYMENT_CAN_VIEW";
        
    public const string MUSHAK_RETURN_MUSHAK_RETURN_PAYMENT_CAN_ADD = "MUSHAK_RETURN_MUSHAK_RETURN_PAYMENT_CAN_ADD";
    public const string MUSHAK_RETURN_MUSHAK_RETURN_PAYMENT_CAN_ADD_CHALAN_NO = "MUSHAK_RETURN_MUSHAK_RETURN_PAYMENT_CAN_ADD_CHALAN_NO";
    public const string MUSHAK_RETURN_MUSHAK_RETURN_PAYMENT_CAN_PRINT_TR6 = "MUSHAK_RETURN_MUSHAK_RETURN_PAYMENT_CAN_PRINT_TR6";
       
    public const string MUSHAK_RETURN_MUSHAK_RETURN_REFUND_CAN_VIEW = "MUSHAK_RETURN_MUSHAK_RETURN_REFUND_CAN_VIEW";
        
    public const string MUSHAK_RETURN_MUSHAK_RETURN_REFUND_CAN_ADD = "MUSHAK_RETURN_MUSHAK_RETURN_REFUND_CAN_ADD";
    public const string MUSHAK_RETURN_MUSHAK_RETURN_REFUND_CAN_ADD_APPROVED_REFUND = "MUSHAK_RETURN_MUSHAK_RETURN_REFUND_CAN_ADD_APPROVED_REFUND";
    public const string MUSHAK_RETURN_MUSHAK_RETURN_REFUND_CAN_ADD_REFUND_INFO = "MUSHAK_RETURN_MUSHAK_RETURN_REFUND_CAN_ADD_REFUND_INFO";
       
    public const string MUSHAK_RETURN_MUSHAK_SUBMISSIONS_CAN_VIEW = "MUSHAK_RETURN_MUSHAK_SUBMISSIONS_CAN_VIEW";
        
    public const string MUSHAK_RETURN_MUSHAK_SUBMISSIONS_CAN_ADD = "MUSHAK_RETURN_MUSHAK_SUBMISSIONS_CAN_ADD";
    public const string MUSHAK_RETURN_MUSHAK_SUBMISSIONS_9_1_UPLOAD = "MUSHAK_RETURN_MUSHAK_SUBMISSIONS_9_1_UPLOAD";
        
    public const string INTEGRATION_SETUP = "INTEGRATION_SETUP";
    public const string INTEGRATION_SETUP_ADJUSTMENT_TYPE_CAN_VIEW = "INTEGRATION_SETUP_ADJUSTMENT_TYPE_CAN_VIEW";
    public const string INTEGRATION_SETUP_ADJUSTMENT_TYPE_CAN_ADD = "INTEGRATION_SETUP_ADJUSTMENT_TYPE_CAN_ADD";
           
    public const string INTEGRATION_SETUP_BANK_CAN_VIEW = "INTEGRATION_SETUP_BANK_CAN_VIEW";
    public const string INTEGRATION_SETUP_BANK_CAN_ADD = "INTEGRATION_SETUP_BANK_CAN_ADD";
      
       
    public const string INTEGRATION_SETUP_BANK_BRANCH_CAN_VIEW = "INTEGRATION_SETUP_BANK_BRANCH_CAN_VIEW";
    public const string INTEGRATION_SETUP_BANK_BRANCH_CAN_ADD = "INTEGRATION_SETUP_BANK_BRANCH_CAN_ADD";

       
    public const string INTEGRATION_SETUP_CONTRACT_TYPE_CAN_VIEW = "INTEGRATION_SETUP_CONTRACT_TYPE_CAN_VIEW";
    public const string INTEGRATION_SETUP_CONTRACT_TYPE_CAN_ADD = "INTEGRATION_SETUP_CONTRACT_TYPE_CAN_ADD";
      
        
    public const string INTEGRATION_SETUP_COUNTRY_CAN_VIEW = "INTEGRATION_SETUP_COUNTRY_CAN_VIEW";
    public const string INTEGRATION_SETUP_COUNTRY_CAN_ADD = "INTEGRATION_SETUP_COUNTRY_CAN_ADD";

        
    public const string INTEGRATION_SETUP_CUSTOMS_AND_VAT_COMMISSIONARATE_CAN_VIEW = "INTEGRATION_SETUP_CUSTOMS_AND_VAT_COMMISSIONARATE_CAN_VIEW";
    public const string INTEGRATION_SETUP_CUSTOMS_AND_VAT_COMMISSIONARATE_CAN_ADD = "INTEGRATION_SETUP_CUSTOMS_AND_VAT_COMMISSIONARATE_CAN_ADD";

        
    public const string INTEGRATION_SETUP_DELIVERY_METHOD_CAN_VIEW = "INTEGRATION_SETUP_DELIVERY_METHOD_CAN_VIEW";
    public const string INTEGRATION_SETUP_DELIVERY_METHOD_CAN_ADD = "INTEGRATION_SETUP_DELIVERY_METHOD_CAN_ADD";

        
    public const string INTEGRATION_SETUP_DISTRICT_CAN_VIEW = "INTEGRATION_SETUP_DISTRICT_CAN_VIEW";
    public const string INTEGRATION_SETUP_DISTRICT_CAN_ADD = "INTEGRATION_SETUP_DISTRICT_CAN_ADD";
      
     
    public const string INTEGRATION_SETUP_EXPORT_TYPE_CAN_VIEW = "INTEGRATION_SETUP_EXPORT_TYPE_CAN_VIEW";
    public const string INTEGRATION_SETUP_EXPORT_TYPE_CAN_ADD = "INTEGRATION_SETUP_EXPORT_TYPE_CAN_ADD";
     
       
    public const string INTEGRATION_SETUP_MUSHAK_RETURN_PAYMENT_TYPE_CAN_VIEW = "INTEGRATION_SETUP_MUSHAK_RETURN_PAYMENT_TYPE_CAN_VIEW";
    public const string INTEGRATION_SETUP_MUSHAK_RETURN_PAYMENT_TYPE_CAN_ADD = "INTEGRATION_SETUP_MUSHAK_RETURN_PAYMENT_TYPE_CAN_ADD";

        
    public const string INTEGRATION_SETUP_NBR_ECONOMIC_CODE_TYPE_CAN_VIEW = "INTEGRATION_SETUP_NBR_ECONOMIC_CODE_TYPE_CAN_VIEW";
    public const string INTEGRATION_SETUP_NBR_ECONOMIC_CODE_TYPE_CAN_ADD = "INTEGRATION_SETUP_NBR_ECONOMIC_CODE_TYPE_CAN_ADD";

   
    public const string INTEGRATION_SETUP_NBR_ECONOMIC_CODE_CAN_VIEW = "INTEGRATION_SETUP_NBR_ECONOMIC_CODE_CAN_VIEW";
    public const string INTEGRATION_SETUP_NBR_ECONOMIC_CODE_CAN_ADD = "INTEGRATION_SETUP_NBR_ECONOMIC_CODE_CAN_ADD";

    public const string INTEGRATION_SETUP_PAYMENT_METHOD_CAN_VIEW = "INTEGRATION_SETUP_PAYMENT_METHOD_CAN_VIEW";
    public const string INTEGRATION_SETUP_PAYMENT_METHOD_CAN_ADD = "INTEGRATION_SETUP_PAYMENT_METHOD_CAN_ADD";

        
    public const string INTEGRATION_SETUP_PRODUCT_VAT_TYPE_CAN_VIEW = "INTEGRATION_SETUP_PRODUCT_VAT_TYPE_CAN_VIEW";
    public const string INTEGRATION_SETUP_PRODUCT_VAT_TYPE_CAN_ADD = "INTEGRATION_SETUP_PRODUCT_VAT_TYPE_CAN_ADD";

    public const string INTEGRATION_SETUP_PURCHASE_TYPE_CAN_VIEW = "INTEGRATION_SETUP_PURCHASE_TYPE_CAN_VIEW";
    public const string INTEGRATION_SETUP_PURCHASE_TYPE_CAN_ADD = "INTEGRATION_SETUP_PURCHASE_TYPE_CAN_ADD";

       
    public const string INTEGRATION_SETUP_SALES_DELIVERY_TYPE_CAN_VIEW = "INTEGRATION_SETUP_SALES_DELIVERY_TYPE_CAN_VIEW";
    public const string INTEGRATION_SETUP_SALES_DELIVERY_TYPE_CAN_ADD = "INTEGRATION_SETUP_SALES_DELIVERY_TYPE_CAN_ADD";

    public const string INTEGRATION_SETUP_SALES_TYPE_CAN_VIEW = "INTEGRATION_SETUP_SALES_TYPE_CAN_VIEW";
    public const string INTEGRATION_SETUP_SALES_TYPE_CAN_ADD = "INTEGRATION_SETUP_SALES_TYPE_CAN_ADD";

    
    public const string INTEGRATION_SETUP_PURCHASE_REASON_CAN_VIEW = "INTEGRATION_SETUP_PURCHASE_REASON_CAN_VIEW";
    public const string INTEGRATION_SETUP_PURCHASE_REASON_CAN_ADD = "INTEGRATION_SETUP_PURCHASE_REASON_CAN_ADD";

    public const string PRODUCT = "PRODUCT";
        
    public const string PRODUCT_PRODUCT_LIST_CAN_VIEW = "PRODUCT_PRODUCT_LIST_CAN_VIEW";
    public const string PRODUCT_PRODUCT_LIST_CAN_ADD = "PRODUCT_PRODUCT_LIST_CAN_ADD";
    public const string PRODUCT_PRODUCT_LIST_CAN_EDIT = "PRODUCT_PRODUCT_LIST_CAN_EDIT";
    public const string PRODUCT_PRODUCT_LIST_CAN_VIEW_DETAILS = "PRODUCT_PRODUCT_LIST_CAN_VIEW_DETAILS";
    public const string PRODUCT_PRODUCT_LIST_CAN_ADD_SUBMISSION = "PRODUCT_PRODUCT_LIST_CAN_ADD_SUBMISSION";
    public const string PRODUCT_PRODUCT_LIST_CAN_DELETE = "PRODUCT_PRODUCT_LIST_CAN_DELETE";
    public const string PRODUCT_PRODUCT_LIST_CAN_ADD_NEW_PRICE = "PRODUCT_PRODUCT_LIST_CAN_ADD_NEW_PRICE";
    public const string PRODUCT_PRODUCT_LIST_CAN_SET_INPUT_OUTPUT_COEFFICIENT = "PRODUCT_PRODUCT_LIST_CAN_SET_INPUT_OUTPUT_COEFFICIENT";
    public const string PRODUCT_PRODUCT_LIST_CAN_PRINT_MUSHAK_4_3 = "PRODUCT_PRODUCT_LIST_CAN_PRINT_MUSHAK_4_3";
    public const string PRODUCT_PRODUCT_LIST_CAN_ADD_SUPPLIMENTARY_DUTY = "PRODUCT_PRODUCT_LIST_CAN_ADD_SUPPLIMENTARY_DUTY";
    public const string PRODUCT_PRODUCT_LIST_CAN_EDIT_VAT = "PRODUCT_PRODUCT_LIST_CAN_EDIT_VAT";
       
    public const string PRODUCT_DAMAGE_LIST_CAN_VIEW = "PRODUCT_DAMAGE_LIST_CAN_VIEW";
    public const string PRODUCT_DAMAGE_LIST_CAN_ADD = "PRODUCT_DAMAGE_LIST_CAN_ADD";

	public const string PRODUCT_BYPRODUCT_RECEIVE_LIST_CAN_VIEW = "PRODUCT_BYPRODUCT_RECEIVE_LIST_CAN_VIEW";
	public const string PRODUCT_BYPRODUCT_RECEIVE_CAN_ADD = "PRODUCT_BYPRODUCT_RECEIVE_CAN_ADD";
	public const string PRODUCT_BYPRODUCT_RECEIVE_CAN_EDIT = "PRODUCT_BYPRODUCT_RECEIVE_CAN_EDIT";

    #region product Used in service

    public const string PRODUCT_USED_IN_SERVICE_LIST_CAN_VIEW = "PRODUCT_USED_IN_SERVICE_LIST_CAN_VIEW";
    public const string PRODUCT_USED_IN_SERVICE_LIST_CAN_ADD = "PRODUCT_USED_IN_SERVICE_LIST_CAN_ADD";

    #endregion

    public const string THIRD_PARTY = "THIRD_PARTY";

    public const string THIRD_PARTY_VENDOR_CAN_VIEW = "THIRD_PARTY_VENDOR_CAN_VIEW";
    public const string THIRD_PARTY_VENDOR_CAN_ADD = "THIRD_PARTY_VENDOR_CAN_ADD";
    public const string THIRD_PARTY_VENDOR_CAN_EDIT = "THIRD_PARTY_VENDOR_CAN_EDIT";
    public const string THIRD_PARTY_VENDOR_CAN_VIEW_DETAILS = "THIRD_PARTY_VENDOR_CAN_VIEW_DETAILS";

    public const string THIRD_PARTY_CUSTOMER_CAN_VIEW = "THIRD_PARTY_CUSTOMER_CAN_VIEW";
    public const string THIRD_PARTY_CUSTOMER_CAN_ADD = "THIRD_PARTY_CUSTOMER_CAN_ADD";
    public const string THIRD_PARTY_CUSTOMER_CAN_EDIT = "THIRD_PARTY_CUSTOMER_CAN_EDIT";
    public const string THIRD_PARTY_CUSTOMER_CAN_DELETE = "THIRD_PARTY_CUSTOMER_CAN_DELETE";

    public const string PURCHASE = "PURCHASE";        
    public const string PURCHASE_PURCHASE_LIST_CAN_VIEW = "PURCHASE_PURCHASE_LIST_CAN_VIEW";
    public const string PURCHASE_PURCHASE_LIST_CAN_ADD = "PURCHASE_PURCHASE_LIST_CAN_ADD";
    public const string PURCHASE_PURCHASE_LIST_CAN_ADD_DEBIT_NOTE = "PURCHASE_PURCHASE_LIST_CAN_ADD_DEBIT_NOTE";
    public const string PURCHASE_PURCHASE_LIST_CAN_VIEW_DETAILS = "PURCHASE_PURCHASE_LIST_CAN_VIEW_DETAILS";
    public const string PURCHASE_PURCHASE_LIST_CAN_PRINT_MUSHAK_6_8 = "PURCHASE_PURCHASE_LIST_CAN_PRINT_MUSHAK_6_8";
    public const string PURCHASE_PURCHASE_LIST_CAN_PRINT_MUSHAK_6_7 = "PURCHASE_PURCHASE_LIST_CAN_PRINT_MUSHAK_6_7";
    
    public const string PURCHASE_PURCHASE_VDS_LIST_CAN_VIEW = "PURCHASE_PURCHASE_VDS_LIST_CAN_VIEW";
    public const string PURCHASE_PURCHASE_VDS_LIST_CAN_ADD_VDS_REPORT = "PURCHASE_PURCHASE_VDS_LIST_CAN_ADD_VDS_REPORT";
  
    public const string PURCHASE_PURCHASE_DUE_LIST_CAN_VIEW = "PURCHASE_PURCHASE_DUE_LIST_CAN_VIEW";
    public const string PURCHASE_PURCHASE_DUE_LIST_CAN_ADD_PAYMENT = "PURCHASE_PURCHASE_DUE_LIST_CAN_ADD_PAYMENT";

    public const string PRODUCTION = "PRODUCTION";
  
    public const string PRODUCTION_PRODUCTION_LIST_CAN_VIEW = "PRODUCTION_PRODUCTION_LIST_CAN_VIEW";
    public const string PRODUCTION_PRODUCTION_LIST_CAN_ADD = "PRODUCTION_PRODUCTION_LIST_CAN_ADD";
     
    public const string PRODUCTION_CONTRACTUAL_PRODUCTION_CAN_VIEW = "PRODUCTION_CONTRACTUAL_PRODUCTION_CAN_VIEW";
    public const string PRODUCTION_CONTRACTUAL_PRODUCTION_CAN_ADD = "PRODUCTION_CONTRACTUAL_PRODUCTION_CAN_ADD";
    public const string PRODUCTION_CONTRACTUAL_PRODUCTION_CAN_ADD_TRANSFER = "PRODUCTION_CONTRACTUAL_PRODUCTION_CAN_ADD_TRANSFER";
    public const string PRODUCTION_CONTRACTUAL_PRODUCTION_CAN_ADD_RAW = "PRODUCTION_CONTRACTUAL_PRODUCTION_CAN_ADD_RAW";
    public const string PRODUCTION_CONTRACTUAL_PRODUCTION_CAN_ADD_PRODUCTION_TRANSFER = "PRODUCTION_CONTRACTUAL_PRODUCTION_CAN_ADD_PRODUCTION_TRANSFER";
       
    public const string PRODUCTION_TRANSFER_LIST_CAN_VIEW = "PRODUCTION_TRANSFER_LIST_CAN_VIEW";
    public const string PRODUCTION_TRANSFER_LIST_CAN_VIEW_DETAILS = "PRODUCTION_TRANSFER_LIST_CAN_VIEW_DETAILS";

    public const string SALE = "SALE";

    public const string SALE_CAN_VERIFY = "SALE_CAN_VERIFY";
    public const string SALE_SALE_LIST_CAN_VIEW = "SALE_SALE_LIST_CAN_VIEW";
    public const string SALE_SALE_LIST_CAN_ADD = "SALE_SALE_LIST_CAN_ADD";
    public const string SALE_SALE_LIST_CAN_ADD_CREDIT_NOTE = "SALE_SALE_LIST_CAN_ADD_CREDIT_NOTE";
    public const string SALE_SALE_LIST_CAN_VIEW_DETAILS = "SALE_SALE_LIST_CAN_VIEW_DETAILS";
   
    public const string SALE_SALE_VDS_LIST_CAN_VIEW = "SALE_SALE_VDS_LIST_CAN_VIEW";
    public const string SALE_SALE_VDS_LIST_CAN_ADD_VDS_RECEIVE = "SALE_SALE_VDS_LIST_CAN_ADD_VDS_RECEIVE";
      
    public const string SALE_SALE_DUE_CAN_VIEW = "SALE_SALE_DUE_CAN_VIEW";
    public const string SALE_SALE_DUE_CAN_ADD_SALES_RECEIVE = "SALE_SALE_DUE_CAN_ADD_SALES_RECEIVE";

    public const string REPORTS = "REPORTS";
	public const string REPORTS_DEBIT_NOTE_DETAILS_LIST_REPORT = "REPORTS_DEBIT_NOTE_DETAILS_LIST_REPORT";
	public const string REPORTS_CREDIT_NOTE_DETAILS_LIST_REPORT = "REPORTS_CREDIT_NOTE_DETAILS_LIST_REPORT";
	public const string REPORTS_SALES_DETAILS_LIST_REPORT = "REPORTS_SALES_DETAILS_LIST_REPORT";
	public const string REPORTS_PURCHASE_DETAILS_LIST_REPORT = "REPORTS_PURCHASE_DETAILS_LIST_REPORT";
    public const string REPORTS_SALES_PRODUCT_LIST_REPORT = "REPORTS_SALES_PRODUCT_LIST_REPORT";
    public const string REPORTS_PRODUCT_CURRENT_STOCK = "REPORTS_PRODUCT_CURRENT_STOCK";
    public const string REPORTS_PURCHASE_PRODUCT_LIST_REPORT = "REPORTS_PURCHASE_PRODUCT_LIST_REPORT";
    public const string REPORTS_PURCHASE_REPORT_BY_VENDOR = "REPORTS_PURCHASE_REPORT_BY_VENDOR";
    public const string REPORTS_PURCHASE_REPORT_BY_VENDOR_CAN_VIEW = "REPORTS_PURCHASE_REPORT_BY_VENDOR_CAN_VIEW";
    public const string REPORTS_PURCHASE_REPORT_BY_GR_NO = "REPORTS_PURCHASE_REPORT_BY_GR_NO";
    public const string REPORTS_PURCHASE_REPORT_BY_GR_NO_CAN_VIEW = "REPORTS_PURCHASE_REPORT_BY_GR_NO_CAN_VIEW";
    public const string REPORTS_FOR_EXPENSE = "REPORTS_FOR_EXPENSE";
    public const string REPORTS_FOR_EXPENSE_CAN_VIEW = "REPORTS_FOR_EXPENSE_CAN_VIEW";
    public const string REPORTS_MONTHLY_PURCHASE_REPORT = "REPORTS_MONTHLY_PURCHASE_REPORT";
    public const string REPORTS_MONTHLY_PURCHASE_REPORT_CAN_VIEW = "REPORTS_MONTHLY_PURCHASE_REPORT_CAN_VIEW";
    public const string REPORTS_DAMAGE_REPORT = "REPORTS_DAMAGE_REPORT";
    public const string REPORTS_DAMAGE_REPORT_CAN_VIEW = "REPORTS_DAMAGE_REPORT_CAN_VIEW";
    public const string REPORTS_DAMAGE_REPORT_CAN_PRINT = "REPORTS_DAMAGE_REPORT_CAN_PRINT";
    public const string REPORTS_VENDOR_REPORT = "REPORTS_VENDOR_REPORT";
    public const string REPORTS_VENDOR_REPORT_CAN_VIEW = "REPORTS_VENDOR_REPORT_CAN_VIEW";
    public const string REPORTS_VENDOR_REPORT_CAN_PRINT = "REPORTS_VENDOR_REPORT_CAN_PRINT";
    public const string REPORTS_CUSTOMER_REPORT = "REPORTS_CUSTOMER_REPORT";
    public const string REPORTS_ALL_CUSTOMER_REPORT = "REPORTS_ALL_CUSTOMER_REPORT";
    public const string REPORTS_CUSTOMER_REPORT_CAN_VIEW = "REPORTS_CUSTOMER_REPORT_CAN_VIEW";
    public const string REPORTS_CUSTOMER_REPORT_CAN_PRINT = "REPORTS_CUSTOMER_REPORT_CAN_PRINT";
    public const string REPORTS_SALES_REPORT = "REPORTS_SALES_REPORT";
    public const string REPORTS_SALES_REPORT_CAN_VIEW = "REPORTS_SALES_REPORT_CAN_VIEW";
    public const string REPORTS_SALES_REPORT_CAN_PRINT = "REPORTS_SALES_REPORT_CAN_PRINT";
    public const string REPORTS_PURCHASE_REPORT = "REPORTS_PURCHASE_REPORT";
    public const string REPORTS_PURCHASE_REPORT_CAN_VIEW = "REPORTS_PURCHASE_REPORT_CAN_VIEW";
    public const string REPORTS_PURCHASE_REPORT_CAN_PRINT = "REPORTS_PURCHASE_REPORT_CAN_PRINT";
    public const string REPORTS_AUDIT_LOG_REPORT = "REPORTS_AUDIT_LOG_REPORT";
    public const string REPORTS_AUDIT_LOG_REPORT_CAN_VIEW = "REPORTS_AUDIT_LOG_REPORT_CAN_VIEW";
    public const string REPORTS_AUDIT_LOG_REPORT_CAN_PRINT = "REPORTS_AUDIT_LOG_REPORT_CAN_PRINT";
    public const string REPORTS_PRODUCTION_REPORT = "REPORTS_PRODUCTION_REPORT";
    public const string REPORTS_PRODUCTION_REPORT_CAN_VIEW = "REPORTS_PRODUCTION_REPORT_CAN_VIEW";
    public const string REPORTS_PRODUCTION_REPORT_CAN_PRINT = "REPORTS_PRODUCTION_REPORT_CAN_PRINT";
    public const string REPORTS_USERS_REPORT = "REPORTS_USERS_REPORT";
    public const string REPORTS_USERS_REPORT_CAN_VIEW = "REPORTS_USERS_REPORT_CAN_VIEW";
    public const string REPORTS_USERS_REPORT_CAN_PRINT = "REPORTS_USERS_REPORT_CAN_PRINT";
    public const string REPORTS_CONTRACTUAL_PRODUCTION_REPORT = "REPORTS_CONTRACTUAL_PRODUCTION_REPORT";
    public const string REPORTS_CONTRACTUAL_PRODUCTION_REPORT_CAN_VIEW = "REPORTS_CONTRACTUAL_PRODUCTION_REPORT_CAN_VIEW";
    public const string REPORTS_CONTRACTUAL_PRODUCTION_REPORT_CAN_PRINT = "REPORTS_CONTRACTUAL_PRODUCTION_REPORT_CAN_PRINT";
    public const string REPORTS_SALES_VDS_LIST_REPORT = "REPORTS_SALES_VDS_LIST_REPORT";
    public const string REPORTS_SALES_VDS_LIST_REPORT_CAN_VIEW = "REPORTS_SALES_VDS_LIST_REPORT_CAN_VIEW";
    public const string REPORTS_SALES_VDS_LIST_REPORT_CAN_PRINT = "REPORTS_SALES_VDS_LIST_REPORT_CAN_PRINT";
    public const string REPORTS_PURCHASE_VDS_LIST_REPORT = "REPORTS_PURCHASE_VDS_LIST_REPORT";
    public const string REPORTS_PURCHASE_VDS_LIST_REPORT_CAN_VIEW = "REPORTS_PURCHASE_VDS_LIST_REPORT_CAN_VIEW";
    public const string REPORTS_PURCHASE_VDS_LIST_REPORT_CAN_PRINT = "REPORTS_PURCHASE_VDS_LIST_REPORT_CAN_PRINT";
    public const string REPORTS_TRANSFER_RAW_MATERIAL_REPORT = "REPORTS_TRANSFER_RAW_MATERIAL_REPORT";
    public const string REPORTS_TRANSFER_RAW_MATERIAL_REPORT_CAN_VIEW = "REPORTS_TRANSFER_RAW_MATERIAL_REPORT_CAN_VIEW";
    public const string REPORTS_TRANSFER_RAW_MATERIAL_REPORT_CAN_PRINT = "REPORTS_TRANSFER_RAW_MATERIAL_REPORT_CAN_PRINT";
    public const string MUSHAK = "MUSHAK";
    public const string MUSHAK_MUSHAK_2_1 = "MUSHAK_MUSHAK_2_1";
    public const string MUSHAK_MUSHAK_2_1_CAN_VIEW = "MUSHAK_MUSHAK_2_1_CAN_VIEW";
    public const string MUSHAK_MUSHAK_2_3 = "MUSHAK_MUSHAK_2_3";
    public const string MUSHAK_MUSHAK_2_3_CAN_VIEW = "MUSHAK_MUSHAK_2_3_CAN_VIEW";
    public const string MUSHAK_MUSHAK_4_3 = "MUSHAK_MUSHAK_4_3";
    public const string MUSHAK_MUSHAK_4_3_CAN_VIEW = "MUSHAK_MUSHAK_4_3_CAN_VIEW";
    public const string MUSHAK_MUSHAK_4_4 = "MUSHAK_MUSHAK_4_4";
    public const string MUSHAK_MUSHAK_4_4_CAN_VIEW = "MUSHAK_MUSHAK_4_4_CAN_VIEW";
    public const string MUSHAK_MUSHAK_4_5 = "MUSHAK_MUSHAK_4_5";
    public const string MUSHAK_MUSHAK_4_5_CAN_VIEW = "MUSHAK_MUSHAK_4_5_CAN_VIEW";
    public const string MUSHAK_MUSHAK_6_1 = "MUSHAK_MUSHAK_6_1";
    public const string MUSHAK_MUSHAK_6_1_CAN_VIEW = "MUSHAK_MUSHAK_6_1_CAN_VIEW";
    public const string MUSHAK_MUSHAK_6_2_1 = "MUSHAK_MUSHAK_6_2_1";
    public const string MUSHAK_MUSHAK_6_2_1_CAN_VIEW = "MUSHAK_MUSHAK_6_2_1_CAN_VIEW";
    public const string MUSHAK_MUSHAK_6_2 = "MUSHAK_MUSHAK_6_2";
    public const string MUSHAK_MUSHAK_6_2_CAN_VIEW = "MUSHAK_MUSHAK_6_2_CAN_VIEW";
    public const string MUSHAK_MUSHAK_6_3 = "MUSHAK_MUSHAK_6_3";
    public const string MUSHAK_MUSHAK_6_3_CAN_VIEW = "MUSHAK_MUSHAK_6_3_CAN_VIEW";
    public const string MUSHAK_MUSHAK_6_4 = "MUSHAK_MUSHAK_6_4";
    public const string MUSHAK_MUSHAK_6_4_CAN_VIEW = "MUSHAK_MUSHAK_6_4_CAN_VIEW";
    public const string MUSHAK_MUSHAK_6_5 = "MUSHAK_MUSHAK_6_5";
    public const string MUSHAK_MUSHAK_6_5_CAN_VIEW = "MUSHAK_MUSHAK_6_5_CAN_VIEW";
    public const string MUSHAK_MUSHAK_6_6 = "MUSHAK_MUSHAK_6_6";
    public const string MUSHAK_MUSHAK_6_6_CAN_VIEW = "MUSHAK_MUSHAK_6_6_CAN_VIEW";
    public const string MUSHAK_MUSHAK_6_7 = "MUSHAK_MUSHAK_6_7";
    public const string MUSHAK_MUSHAK_6_7_CAN_PRINT = "MUSHAK_MUSHAK_6_7_CAN_PRINT";
    public const string MUSHAK_MUSHAK_6_8 = "MUSHAK_MUSHAK_6_8";
    public const string MUSHAK_MUSHAK_6_8_CAN_PRINT = "MUSHAK_MUSHAK_6_8_CAN_PRINT";
    public const string MUSHAK_MUSHAK_6_10 = "MUSHAK_MUSHAK_6_10";
    public const string MUSHAK_MUSHAK_6_10_CAN_VIEW = "MUSHAK_MUSHAK_6_10_CAN_VIEW";
    public const string MUSHAK_MUSHAK_9_1 = "MUSHAK_MUSHAK_9_1";
    public const string MUSHAK_MUSHAK_9_1_CAN_VIEW = "MUSHAK_MUSHAK_9_1_CAN_VIEW";
    public const string MUSHAK_MUSHAK_9_1_CAN_PRINT = "MUSHAK_MUSHAK_9_1_CAN_PRINT";
    public const string AUDIT = "AUDIT";
    public const string AUDIT_LOGS_CAN_VIEW = "AUDIT_LOGS_CAN_VIEW";
  
    public const string AUDIT_LOGS_CAN_VIEW_DETAILS = "AUDIT_LOGS_CAN_VIEW_DETAILS";

    public const string AdministrationBrandCanView = "ADMINISTRATION_BRAND_CAN_VIEW";
    public const string AdministrationBrandCanAdd = "ADMINISTRATION_BRAND_CAN_ADD";
    public const string AdministrationBrandCanEdit = "ADMINISTRATION_BRAND_CAN_EDIT";

    #region Miscellaneus Report

    public const string YEARLY_COMPARISON_REPORT = "YEARLY_COMPARISON_REPORT";
    public const string MONTHLY_COMPARISON_REPORT = "MONTHLY_COMPARISON_REPORT";

    #endregion

}

public class VMSDateFormat
{
    public static string INPUT_DATE_FORMAT = "MM/dd/yyyy";
}